### ISSUE TITLE
Removing series from legend

### ISSUE THREAD

**Issue by fstolz** [timmolter/XChart#100]
Hi,
I have a chart with several series. I want to show only some particular series names in the legend and leave the other ones out. Would it be possible to implement this function?

Regards,
fstolz

**Comment by timmolter** [comment]
Use a blacklist and whitelist for this.

**Comment by timmolter** [comment]
Done. See `LineChart07` in V3.0.0 on develop branch and/or snapshot jars. Use `series.setShowInLegend()`.
