### ISSUE TITLE
Unresolved dependencies de.erichseifert.vectorgraphics2d

### ISSUE THREAD

**Issue by sidec** [timmolter/XChart#102]
I got error when trying to use maven artifacts with sbt. It reports:

```bash
[error] (*:update) sbt.ResolveException: unresolved dependency: de.erichseifert.vectorgraphics2d#VectorGraphics2D;0.9.1: not found
[error] Total time: 2 s, completed 01-Apr-2015 22:56:50
```

I was trying both latest release (2.4.3) and snapshot.

**Comment by timmolter** [comment]
What is sbt?

**Comment by sidec** [comment]
sbt uses Apache Ivy to implement managed dependencies in scala projects. I'm trying to use XChart in scala application. There is no issues with XChart < 2, so I suppose it is not problem specific to language I'm using.

**Comment by chrsoo** [comment]
Hi,
I have the same issue, seems like sbt/ivy does not respect optional Maven dependencies. In any case, the `VectorGraphics2D` library can be excluded from the SBT build like so:

```
libraryDependencies += "com.xeiam.xchart" % "xchart" % "2.5.0" exclude("de.erichseifert.vectorgraphics2d", "VectorGraphics2D") withSources()
```

@timmolter Maybe add a note in the README.md about the optional  `VectorGraphics2D` library and a pointer to where the right version can be obtained? Forking and creating a pull request for changing the README.md. Feel free to ignore if you feel it is not relevant... :-)

**Comment by timmolter** [comment]
@chrsoo Thanks for figuring that out and taking the time to let others know about it. :)
