### ISSUE TITLE
Save as EPS

### ISSUE THREAD

**Issue by hwaipy** [timmolter/XChart#105]
There seems some problem when I try to save a chart as EPS or PDF.

I run demo com.xeiam.xchart.standalone.Example1 and get a serials of files. Although the bitmaps appears to be correct,
![sample_chart](https://cloud.githubusercontent.com/assets/6906967/7514624/c06cc716-f4f1-11e4-9134-b0707db3c9d5.png)
the eps and pdf has something wrong with text.
![qq20150507-1 2x](https://cloud.githubusercontent.com/assets/6906967/7514653/fc5cf246-f4f1-11e4-86cf-8fe67678ab60.png)

I tried to output eps using Apache xmlgraphics-commons, it seems good. So is there something wrong with VectorGraphics2D?

**Comment by timmolter** [comment]
Thanks for reporting the issue. I just ran a test and the PDF looks fine, but the EPS file is not (as you reported). It could be a problem with `VectorGraphics2D`, especially if you say EPS export works fine with `xmlgraphics-commons`. 

Are you using version 3.5.0?

**Comment by hwaipy** [comment]
In my test results, the PDF looks better than EPS, but still not correct, as shown below.
![qq20150507-1 2x](https://cloud.githubusercontent.com/assets/6906967/7514894/7a030c06-f4f4-11e4-9fc8-3aaec8fffa23.png)


I'm using XChart-2.5.0, xmlgraphics-commons-1.5. What do you mean for version 3.5.0?

**Comment by timmolter** [comment]
Whoops, I meant 2.5.0 xchart.

What exactly is not correct withthe PDF version? I don't see it. The font size perhaps?

If `xmlgraphics-commons` works better, I'd be happy to use that lib instead.

**Comment by hwaipy** [comment]
The 'Y' is missing in PDF.

I'm not familiar with both xmlgraphics-commons and VectorGraphics2D. So I can't offer further suggestion. Maybe xmlgraphics-commons would be more robust as an Apache production. haha.

**Comment by timmolter** [comment]
Wow, I can't believe I missed that. I think `xmlgraphics-commons` would be more robust. It doesn't look like it does SVGs though. Although `VectorGraphics2D` does a good job at SVGs.

**Comment by timmolter** [comment]
I made a fix for the PDF issue. EPS still has issues.

**Comment by timmolter** [comment]
https://github.com/eseifert/vectorgraphics2d/issues/27#event-420240280

3rd party dependency fixed this issue now.

**Comment by timmolter** [comment]
release 2.5.1 should contain the fix.
