### ISSUE TITLE
200 mBTC Bounty - Support Stacked Bar Charts

### ISSUE THREAD

**Issue by lucasgray** [timmolter/XChart#108]
Hey Tim, thanks for the charting library!  Looks great.

It would be excellent to support Stacked Bar charts, like these

https://developers.google.com/chart/interactive/docs/gallery/barchart#stacked-bar-charts

Both as 100% stacked, and the absolute stacked.

What do you think?

**Comment by timmolter** [comment]
Thanks for the compliment. I'll put it on my todo list. Adding that feature should be quite easy. Right now, I have no time, but hopefully in a month or two...

**Comment by lucasgray** [comment]
Cool.  Drop a note when you start.  We may have a need before that and may give it a whirl ourselves.  Also eyeing that pie chart request.

**Comment by ge0rg0** [comment]
Hi there. I started looking at this one. How does this bounty thing works?
Best regards,
George

**Comment by timmolter** [comment]
@ge0rg0 Just create a Pull request with the new feature. I can review it, give feedback, you'll probably ahve to tweak a few things. When finally accepted, give me your BTC address, and I'll pay you.

**Comment by joshafest** [comment]
I have found an tricky solution to this.....
So, i want to show you a demo of this ....just a simple not heavily codes.
should i email you or creat pull request?

**Comment by joshafest** [comment]
I have created pull request.....of this....have a look over xchart-demo...../bar/BarChatStack.java
I know it is not the absolute stack but work similar to that .......well the implement of new thing can make xchart a heavy weight which should not be ok......so , I used overlapping trick,
Any way ,  I deserve atleast 2/3 of the bounty.....
 15uLL8vUCr6XtEt5Cr8G5TtWtCWNZSdDeZ   my btc address
donate if you can...
![output-of-barchartstack](https://cloud.githubusercontent.com/assets/12095370/13371916/c5cbc820-dd57-11e5-8973-46a3666df5b2.PNG)

**Comment by joshafest** [comment]
if you want to do lib I will do it also, but ....I done it because I need urgent money(btc) ...to make lib I have to go through the whole code

**Comment by ge0rg0** [comment]
Hi, 

I commited a more generic solution, which I started working on some time ago. I created a demo file based on the example done by @joshafest

**Comment by joshafest** [comment]
he need new functionality not an...just examples using old one.....well ....i am just near  to complete the functionality....lol...

**Comment by ge0rg0** [comment]
It is new functionality, just the demo data is the same. I can create new demo data.

**Comment by joshafest** [comment]
i mean to say ..   ...he did not need overlaping    ....if your do not have that than ok....let him reply...

**Comment by joshafest** [comment]
I am working on it....but some trouble with zero transform and yTransform.
Moreover if we replace (zeroOffset) with (zeroOffset - yOffset) the bar should became a horizontal line but it is not happening.

**Comment by joshafest** [comment]
I am very near to crack this issue.

**Comment by timmolter** [comment]
Done. try with latest snapshot jar. `BarChart03` demos it.
