### ISSUE TITLE
Wrong bars placement when ticks are hidden

### ISSUE THREAD

**Issue by paolieri** [timmolter/XChart#111]
When some ticks are hidden (e.g., only 2, 4, 6, 8, 12 x-ticks are shown), bars are not placed at the correct x-position.

For example, this code:
```java
public class XChartBug {
    public static void main(String[] args) {
        int[] x = new int[] {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
        int[] y = new int[] {1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0};
        
        Chart chart = new ChartBuilder().chartType(ChartType.Bar).width(640).height(480).build();
        chart.addSeries("test", x, y);
        chart.getStyleManager().setLegendVisible(false);
        new SwingWrapper(chart).displayChart();
    }
}
````
produces the plot:

![image](https://cloud.githubusercontent.com/assets/1083642/10126108/0d6c3718-658b-11e5-993f-5b33a84711a3.png)

By dropping the last bar, all x-ticks are shown, and the placement of bars is correct:

![image](https://cloud.githubusercontent.com/assets/1083642/10126112/38d0c57c-658b-11e5-92ca-78e0f5b6d254.png)

**Comment by timmolter** [comment]
Thanks for reporting this. I'll look into it.

**Comment by timmolter** [comment]
fixed. Try latest snapshot jar please.

**Comment by paolieri** [comment]
Hi Tim!

With the latest snapshot, it works perfectly. Thank you for your promptness in fixing this, and also for XChart itself: it has a nice API and really fills a need.

P.S. To get the latest snapshot, I had to use the groupId "com.xeiam.xchart", not "com.xeiam" (suggested in the [README](https://github.com/timmolter/XChart/blob/develop/README.md).

**Comment by timmolter** [comment]
You're welcome. I appreciate the feedback!
