### ISSUE TITLE
Bar charts with values above bars

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChart#112]
https://stackoverflow.com/questions/30883946/java-xeiams-xchart-marker-with-values

**Comment by eleanora** [comment]
Hi Tim, any updates regarding this feature? Would be really great to have this feature.

**Comment by timmolter** [comment]
I'd love to do it, but I'm busy ATM. I'll see if I can make some time soon.

**Comment by Xmasss** [comment]
Hi Tim, I also need this feature. Can you please notice us when we can expect it.

**Comment by timmolter** [comment]
OK, I'll put it on my todo list. Maybe a week or two.

**Comment by timmolter** [comment]
Done. See latest snapshot jar (see README). Will come out in next official release.
