### ISSUE TITLE
Legend width is included even if it's marked as invisible

### ISSUE THREAD

**Issue by TickleThePanda** [timmolter/XChart#113]
Legend width is included here: https://github.com/timmolter/XChart/blob/develop/xchart/src/main/java/com/xeiam/xchart/internal/chartpart/Axis.java#L155

(legend padding is correctly ignored: https://github.com/timmolter/XChart/blob/develop/xchart/src/main/java/com/xeiam/xchart/internal/chartpart/Axis.java#L179 )

**Comment by timmolter** [comment]
Thanks. I don't think this has an affect though. `getSizeHint` returns zero as the legend size:
   if (!chartPainter.getStyleManager().isLegendVisible()) {
      return new double[] { 0, 0 };
    }

Did you notice a problem with a chart rendering?

**Comment by timmolter** [comment]
https://github.com/timmolter/XChart/commit/bff01674ea7700eb15391eb7be7bd8d591112bdd
