### ISSUE TITLE
Bar chart - allow null values in data series. 

### ISSUE THREAD

**Issue by eleanora** [timmolter/XChart#119]
First, xchart is great so thanks for all the great work.

Say that we have series 1 and series 2. 
Series 1 contains values for A and B  and series 2 contain values for B and C (A, B and C are the x axis labels). 
This kind of bar chart is impossible to present using xchart since I can't pass null values for C in series 1 and A in series 2.

Also, if you do decide to add this feature I think that the null values should not create blank spaces of missing bars. In my opinion, the bars should be one next to the other without blank spaces.

This is a very common use case and I would really appreciate it if you consider adding this feature to xchart.

**Comment by timmolter** [comment]
Done. See latest snapshot jar or code.

**Comment by eleanora** [comment]
I'm getting "X-Axis data must be of type Number or Date for X-Y chart types!!!" when I create a series with null values and then add that series to the bar chart.
Can you please send me an example? (How can I add a series with null values?)
