### ISSUE TITLE
Unable to use QuickChart.getChart with the List<Numbers> parameters

### ISSUE THREAD

**Issue by Ramh5** [timmolter/XChart#120]
Using the most simple example0.java (http://knowm.org/open-source/xchart/xchart-example-code/) works just fine. However I am not able to use the 3rd getChart methode, the one with List parameters instead of Arrays.

Methode Javadoc
http://knowm.org/javadocs/xchart/org/knowm/xchart/QuickChart.html#getChart-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.util.List-java.util.List-

With the following code I get the following compilation error:

*******************************************************************************************
    import java.util.ArrayList;
    import org.knowm.xchart.Chart;
    import org.knowm.xchart.QuickChart;

    public class XChartTest2 {

      public static void main(String[] args) throws Exception {

        ArrayList<Double> xDataList = new ArrayList<Double>();
        xDataList.add(0.0);
        ArrayList<Double> yDataList = new ArrayList<Double>();
        yDataList.add(0.0);

        // Create Chart
        Chart chartWithList = QuickChart.getChart("Sample Chart", "X", "Y", "y(x)", xDataList, yDataList);
      }
    }
***********************************************************************************************

Compilation error:

    Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	    The method getChart(String, String, String, String, double[], double[]) in the type QuickChart is not applicable for the arguments (String, String, String, String, ArrayList<Double>,     ArrayList<Double>)

	    at XChartTest2.main(XChartTest2.java:16)

**Comment by timmolter** [comment]
Thanks for pointing that out. I pushed a fix. Try the latest SNAPSHOT jar...

**Comment by Ramh5** [comment]
Wow that was the quickest of all quick fix. It seems to work properly now :+1: 

Thanks for the great work, I really enjoy working with XChart (just starting to learn java and GUI so XChart makes it really easy to work include nice graphics into my GUI).

Is there some where we can share our applications once it is finished?

**Comment by timmolter** [comment]
You're welcome! What do you mean by share? There are a few different meanings.

**Comment by Ramh5** [comment]
I mean some kind of forum for people interested in XChart to see what others do with it. And possibly have feed back to improve the application.

**Comment by timmolter** [comment]
No, that doesn't exist. If you wanted to create a Wiki page on this repo, that'd be OK. I could reference it in the README.

**Comment by Ramh5** [comment]
Ok I will keep it in mind I when I am reasonably finished with my first application. I am making a GUI to log and display child weight vs age against the World Health Organisation data.
