### ISSUE TITLE
Ability to give line graph X values a string description

### ISSUE THREAD

**Issue by jentfoo** [timmolter/XChart#121]
I think this is a feature request more than anything.  I have a need to be able to provide String descriptions for points along the X graph, ideally not even showing the numbers.

A couple thoughts on how to do this would be a possible type that extends `Number`, constructed with a numeric value, and a String which is gathered from .toString().  Then place those .toString() values on the X axis where they belong.

In theory the same thing can be done with dates as well.

Let me know your thoughts, if you have ideas on how this could be done easiest, if I have time I could provide a PR.

**Comment by jentfoo** [comment]
Another (maybe better?) way to accomplish what I need would be to allow a String series for line graphs.  Assume each string is just a distance of `1` from the previous one.  Then on the X axis just display those strings.

**Comment by timmolter** [comment]
@jentfoo After thinking about this, I don't like the idea of extending `Number` or A String series. However, I think what would work is to create another Bar Chart type, where instead of bars, points and lines are drawn.

So perhaps the solution is to change the Bar Chart into a Category Chart, and be able to set the series type, bar being the default. Then everything is the same except right at the end when the data is drawn, it just checks what to draw and draws either bars or lines, etc.

**Comment by jentfoo** [comment]
Seems resonable.  Any idea how much effort it will be?  Will the bar graph drawing be able to easily share the line drawing code of the line graphs??

**Comment by timmolter** [comment]
Should be around 30 minute to an hour of coding and testing.

I don't think it will be easily able to share. Maybe you could make a `SeriesDrawer` class with static methods to draw the various series types. Otherwise copypasta it, and I can clean it up later.

**Comment by timmolter** [comment]
See `BarChart09`. Let me know if that works for you.

**Comment by jentfoo** [comment]
@timmolter I can make that work.  A few considerations with this style:

* If you want the lines to all match the x axis you need to "chart.getStyleManager().setBarWidthPercentage(0)".  Otherwise it seems the lines are staggered based off a now invisible bar width.  Seems like a kind of awkward hidden detail.  Maybe this should be automatically set with that style?

* The y axis values are no longer automatically scaled.  As you can see in my latest version, the y axis minimum is auto scaled to to be relative to the dataset.
![priorityschedulerexecute](https://cloud.githubusercontent.com/assets/2165757/12054769/70f05278-aee3-11e5-8825-26c8d650527d.png)

With your new design the same graph looks like:
![priorityschedulerexecute](https://cloud.githubusercontent.com/assets/2165757/12054803/caae9ab8-aee3-11e5-84db-260e6ea8b89d.png)

Is there a way to get the same Y axis scaling?  I hate to have to put the logic into my apps, but I can if necessary.

**Comment by jentfoo** [comment]
Also, I do think the X axis lines/grid sometimes makes the graph easier to read.  Is it possible to get those back?  If not, it's not a huge deal breaker, but I thought I would at least point it out as another difference.

It does seem like the line graph design is more of a natural fit for displaying this data?

**Comment by timmolter** [comment]
@jentfoo all valid points! I'll work on it. Could you submit a PR, with your above plot code? I'd like to use it to create this new feature and add it to my demo.

**Comment by timmolter** [comment]
> If you want the lines to all match the x axis you need to "chart.getStyleManager().setBarWidthPercentage(0)". Otherwise it seems the lines are staggered based off a now invisible bar width. Seems like a kind of awkward hidden detail. Maybe this should be automatically set with that style?

I don't see what you mean. Can you show me some how?

**Comment by timmolter** [comment]
Please try the latest code and run `LineChart07`.

**Comment by jentfoo** [comment]
@timmolter I just took a look.  It looks like it's working fine for my needs!  I thought I would point out that the logarithmic setting you have enabled in the demo is causing the Y axis to not draw at all.  But as soon as you disable that, it looks great!

Would you like me to open a new issue for that (knowing it's not important to me, but may be to others)?

**Comment by timmolter** [comment]
No, I'll just fix it. Eventually soonish.

**Comment by timmolter** [comment]
Closing. Logarithmic axes doesn't even make sense for this plot. My bad.
