### ISSUE TITLE
Can We Have This New Chart Style?

### ISSUE THREAD

**Issue by imagingbook** [timmolter/XChart#124]
Hello Tim, thanks for this wonderful library! 
Is there any way to obtain a plot like the one shown below?  -- Wilhelm.

![filling-to-axis-plot](https://cloud.githubusercontent.com/assets/3172121/12079014/bbcda57c-b229-11e5-8dda-beffc198bbf6.png)

**Comment by timmolter** [comment]
Not really. You could fake it by trying to make a bar chart with a very small bar width and a second scatter type series.

When I have time, I will add that kind of series style to the regular X-Y chart types.

**Comment by imagingbook** [comment]
Sounds great, thanks!

**Comment by timmolter** [comment]
Done. See `StickChart01` in V3.0.0 on develop branch and/or snapshot jars.
