### ISSUE TITLE
Pie chart - adding support for "set slice label" and "set labels location"

### ISSUE THREAD

**Issue by eleanora** [timmolter/XChart#126]
I think it would be very nice if we could use labels next to each pie chart slice instead of the legend (maybe this could be done by adding another type to the legend position that supports adding legend labels next to the appropriate data series, or as alternative set a label for each series). This way the chart would be more concise. The legend takes additional space that might bother some users (like me..) WDYT? Here's an example for what it might look like:

![image](https://cloud.githubusercontent.com/assets/2756945/12228325/581dbb74-b842-11e5-8dff-ba97cc70ba54.png)

**A few notes regarding this desired feature:**
(1) I noticed that you added percentage inside each slice. It's a good default behavior in my opinion, but it would be nice to be able to set labels to each slice and control the text presented on the slices/next to the slices.
(2) The updated implementation includes percentage inside the slices. I think it should be possible to control the location of the labels as well - next to each slice or inside the slice. The existence of these labels should not be affected by the visibility of the legend (it should be possible to use only the labels - without the legend).
(3) Important - I think it should be possible to add pie charts of same size so that the pie size itself is not affected by the added labels. If one pie chart has certain labels and another has a different set of labels, their size should still be the same somehow. Maybe we need the ability to set the width and height of the pie chart component inside the pie chart window for that to work.

I think this gives more control to the developer over what is presented to the user. I hope you will consider adding this feature. Thanks :)

**Comment by timmolter** [comment]
Definitely will implement those customizations. When time is available next month. If you feel like working on it, that's fine with me as well.

**Comment by timmolter** [comment]
Done. Please see latest 3.0.0 version on develop branch.
