### ISSUE TITLE
Providing feedback

### ISSUE THREAD

**Issue by hugadams** [timmolter/XChart#127]
Hey everyone (@timmolter),

I wanted to drop a line and provide some feedback on xchart.  I just started using this framework last week, and really like it.  Coming from Python to Java, I found the plotting tools to be very idiomatic, low-level and generally frustrating.  For example, in JFreechart, I was importing brush objects to paint lines...

XChart has a very useful API, and I really enjoy using it.  Thank you very much for open-sourcing it.  I've found it be really seamless, especially in supporting streaming data, which many libraries can't handle natively.  

I had a few questions pile up, and hope it's ok to post them here.  These might summarize the few stumbling blocks/gaps that I encountered along the way.

    - Are there any tools available for panning, zooming, selecting data?
    - Is it possible to plot nothing?  I am getting an error when I instantiate a plot without at least one series.  However, I'd really like to have an empty plot until users actually choose something to plot. 
    - What is the correct way to remove data from a plot?  There's no "remove(series...)" method in the API to compliment add and update.
     - Are there any examples available of having a second x-axis?  EG, interval values on the bottom x-axis (0,1,2,3) and timestamps on the top (12:28:15, 12:29:15, ...)

Apart from these issues, I found xchart served my purposes right out of the box, and was much easier to navigate than most java libraries.

Thanks!

**Comment by timmolter** [comment]
Thanks for the compliment! Yes, the state of Java charting libs back in 2011 is exactly why I created XChart with a much cleaner API than what was available.

I'm currently working on V 3.0.0 and I will incorporate your suggestions about an empy chart and removing series. That's a good idea.

For panning, zooming, selecting data, I don't think that's too easy, but I haven't researched it too much. Can you say exactly what you mean? Have you done anything like that with Swing before? Would you need buttons to click or just listen for mouse behaviors? Or what?

**Comment by hugadams** [comment]
Thanks, that sounds great.  

Some plotting frameworks come with a trace/select/zoom tools, to let users interact with regions of the plot dynamically.  I am not familiar with anything in swing, and doubt it would be easy to build these.  Just wanted to double check that anything like this wasn't already in place.

Lastly, it is possible to put labels in the top x-axis or right y-axis?  I didn't see any examples to indicate this was so.

**Comment by timmolter** [comment]
No, that's not possible. Can you show me an example?

**Comment by hugadams** [comment]
Something like this http://stackoverflow.com/questions/10514315/how-to-add-a-second-x-axis-in-matplotlib

**Comment by timmolter** [comment]
Ah, so a second Axis? Like in this open issue: https://github.com/timmolter/XChart/issues/54

We're planning on adding multiple Y-Axes, but not multiple X-Axis.

**Comment by hugadams** [comment]
Cool, thanks.

I do have one more question (sorry) if you don't mind.

I have my plot embedded in a Swing JFrame, and depending on which type of data my user chooses to display, I need to jump between Date axis and number axis.  For example, they may be looking at a time-series plot, but then decide to change the axis from timestamps to intervals completed, which makes for a number axis.  This throws an exception, and the API prevents me from changing the Axis type.

Do you have any suggestions for the most straightforward way to change the axis?  I'd prefer not to have to instantiate an entirely new chart. Between switches, I clear all of my series, so the SeriesMap is clear when the axis type is ready to be changed.

**Comment by timmolter** [comment]
I'd have to tweak the code to handle that situation better. It's on my todo list.

**Comment by timmolter** [comment]
Done with adding and subtracting series and allowing different axes types when new series are removed/added.

See latest develop branch updates and deployed snapshot jar.

For any related issues, please open new and separate issues...

**Comment by hugadams** [comment]
Damn Tim, you're inspiring me to get off my ass and get my own open source shit together.  Thanks man, can probably cut 100 lines of code out of my app now.
