### ISSUE TITLE
Decouple legend from plot

### ISSUE THREAD

**Issue by hugadams** [timmolter/XChart#129]
It would be awesome if it were possible to mess with the legend in a plot, as a standalone object.  For example, when making a plot, I sometimes like to plot *extra* data but have the legend only show a few curves.   If the legend returned some sort of a map, then it would be awesome if we could turn elements on and off.  EG:

     addSeries("foo", xData, yData)
     addSeries("bar", xData, yData)
     getLegend.hideSeires("bar")

**Comment by timmolter** [comment]
The easiest way is have a flag in the Series object `boolean showInLegend`, and you can control it when creating the series. Would that work?

**Comment by timmolter** [comment]
Done. See `LineChart07` in V3.0.0 on develop branch and/or snapshot jars. Use `series.setShowInLegend()`.

**Comment by hugadams** [comment]
Awesome, thanks!
