### ISSUE TITLE
200 mBTC Bounty - Ability to align axes right

### ISSUE THREAD

**Issue by zfoster** [timmolter/XChart#130]
Hi! We love using xcharts and we've dug into quite a bit of customization.

I'm wondering if it's possible to align the y axis numbers to the right, I can't seem to find a configuration option like that. Secondly, is it possible to have bar chart touch the x axis? That is, have the 0 lined up with the x axis and not have padding between the x axis and the 0 even when all numbers are positive. I'd like the charts to not be 'floating' above the axis if possible

<img width="374" alt="screen shot 2016-01-20 at 11 08 22 am" src="https://cloud.githubusercontent.com/assets/1471426/12456649/6da32030-bf66-11e5-806c-6a4722b76bb1.png">

**Comment by timmolter** [comment]
Axis aligning on the right is not yet possible. I'll leave that as a feature request here. The plot content padding is not currently a tweakable parameter, but I can change that. I'll add a note here when it's available.

**Comment by zfoster** [comment]
Thanks a ton, Tim! Appreciate your help, and we love xcharts. Do you accept contributions? We'd likely be willing to try our hand at the axis alignment problem.

**Comment by timmolter** [comment]
Done with padding update. See `BarChart01` on develop branch.

**Comment by timmolter** [comment]
@zfoster You're welcome. Yes we accept donations and put all donations towards bounties to continually improve XChart. You can donate either via the bitcoin address found in the README of via PayPal: http://knowm.org/donate/

Cheers.

**Comment by timmolter** [comment]
@zfoster Thanks for the donation! There are currently some people working on the bounties and we'll use you donation for it. I'll add a bounty to this issue next.

**Comment by billyshea** [comment]
Hm... this should already be possible?

Just add `import `org.knowm.xchart.internal.style.Styler.TextAlignment;` to your program and change the 
alignment with `chart.getStyler().setYAxisLabelAlignment(TextAlignment.Right);` or `    chart.getStyler().setXAxisLabelAlignment(TextAlignment.Left);`.

**Comment by timmolter** [comment]
@billyshea I interpreted what he wanted as moving the entire yAxis over to the right side of the chart. But You could in fact have interpreted it correctly. @zfoster Can you clarify?

**Comment by zfoster** [comment]
That sample chart is exactly what we are looking for. Sorry that we missed it in the api. Thanks @timmolter, @billyshea

**Comment by billyshea** [comment]
Cool. I'm working on request #54, which is similar to what you described @timmolter, although it'll take a little longer. My BTC address is in my profile.

**Comment by billyshea** [comment]
Do I still get the bounty?
