### ISSUE TITLE
Series.setShowInLegend(false) does not disable legend entry

### ISSUE THREAD

**Issue by tgvaughan** [timmolter/XChart#134]
It looks like there's a missing ! in the code.  From [line 72 of Legend_AxesChart] (https://github.com/timmolter/XChart/blob/4421317ca19f5df3fe0b5fe1833087b3a31d95c6/xchart/src/main/java/org/knowm/xchart/internal/chartpart/Legend_AxesChart.java#L72):

```java
      if (series.isShowInLegend()) {
        continue;
      }
```

p.s. thanks for XChart, it's fantastic!

**Comment by timmolter** [comment]
Thanks, fix pushed. Will release 3.0.1 soon.
