### ISSUE TITLE
Labels overlapping?

### ISSUE THREAD

**Issue by spyhunter99** [timmolter/XChart#135]
Just started using this library and so far, i really like it. I've ran into an issue with really long labels. See example below. I'm essentially tracking web service performance and am setting the x axis labels to the URL. Initially the overlay made the labels unreadable, then i found that i can rotate the X labels. So after rotating 45 degrees and setting the text alignment to right, I ran into another issue that I'm not sure how to solve. Some of the ables appear to be misaligned with the columns (building a bar chart here).

Is there anything I can do to fix the misalignment of the x axis labels?

code snippet
````
   Chart_Category barchart = new ChartBuilder_Category()
                      .width(1500)
                      .height(PixelHeightCalc(urls.size()))
                      .title("Average Message Size (bytes)")
                      .xAxisTitle("URL")
                      .yAxisTitle("Average Message Size").theme(ChartTheme.GGPlot2).build();
List<String> urls = <loaded from db>
List<Long> thisdata = <loaded from db>

 barchart.addSeries("size", urls, thisdata);
                barchart.getStyler().setXAxisLabelRotation(45);
                barchart.getStyler().setXAxisLabelAlignment(Styler.TextAlignment.Right);
 BitmapEncoder.saveBitmap(barchart, path + GetFilePathDelimitor() + "image_" + get.getType().toString() + ".png", BitmapFormat.PNG);

````

![image_average_message_size_by_service](https://cloud.githubusercontent.com/assets/1975321/12834288/5ea07974-cb74-11e5-9f0d-4cee6aa27bfe.png)

**Comment by timmolter** [comment]
Hmmm, I'm not sure what the best thing to do is. I'd have to create a test chart and see what I could do as a general solution to large labels.

**Comment by spyhunter99** [comment]
Is there a workaround that I can try? perhaps a limit on the number of characters?

**Comment by timmolter** [comment]
not that I can think of. Maybe truncate the categories on your end before making the chart.
