### ISSUE TITLE
Close chart window without quitting repl

### ISSUE THREAD

**Issue by kindlychung** [timmolter/XChart#137]
I am trying to use XChart in the scala repl, and every time I close the chart window, the repl is terminated.

For example:

```
import org.knowm.xchart.{SwingWrapper, QuickChart}

object UseXchart {
  def main(args: Array[String]) {
    val xData = Array(0.0, 1, 2)
    val yData = Array(2.0, 1, 0)
    val chart = QuickChart.getChart("title", "x", "y", "function", xData, yData)
    val swingChart: SwingWrapper = new SwingWrapper(chart))
    swingChart.displayChart()
  }
}
```

Is there a workaround? Thanks!

**Comment by imagingbook** [comment]
The reason appears to be that SwingWrapper does `setDefaultCloseOperation(EXIT_ON_CLOSE)` on its JFrame, which is returned by `displayChart()`. Something like this might work in Java (don't know about Scala):

`swingChart.displayChart().setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE)`

--Wilhelm

**Comment by timmolter** [comment]
Thanks, @imagingbook If someone can figure out a solution that works for Java and Scala, then I'm more than happy to integrate the fix.

**Comment by imagingbook** [comment]
I suggest to simply replace `EXIT_ON_CLOSE` by `HIDE_ON_CLOSE` in the `SwingWrapper.displayChartMatrix()` method.I see no reason for terminating the entire application when a frame is closed.

--Wilhelm

**Comment by timmolter** [comment]
@imagingbook The Swing Wrapper is just a convenience class intended to be an app. The Exit on close is intentional. 

@kindlychung For creating custom apps, you can use `XChartPanel` as demonstrated in `SwingWrapper`, but with any other code necessary for your app. Or try @imagingbook 's initial suggestion.

**Comment by UPocek** [comment]
This worked for me: `new SwingWrapper(pieChart).displayChart().setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);`
