### ISSUE TITLE
How do I contirubute

### ISSUE THREAD

**Issue by dluzzon** [timmolter/XChart#138]
Hi, you are really doing good job there.
I have one file that was enhanced. adding some more colors.

would like to promote it / send it to you.

Please let me know the way.

thanks.
Danny.

**Comment by timmolter** [comment]
The best and most obvious way is to create a pull request via github. That's what everyone does. You can google about how to do that. If you want to be lazy and not learn that, and it's just a tiny bit of code, just paste it here, and I'll take a look and merge it myself.

**Comment by dluzzon** [comment]
ok, did commit.
let me know if you able to get it.
if you want it on new branch let me know as well. 
it was done on development branch.

**Comment by timmolter** [comment]
You need to create a pull request next before I see anything...

**Comment by dluzzon** [comment]
בס"ד

 

Hi, failing to do so,

Validation error.

"it looks you have no privileges to do this request" (something like this).

 

What I did:

Create mew branch

Commit

Pull Request

Getting the error message above.

 

Same was when trying to do direct to development branch.

**Comment by timmolter** [comment]
Did you first fork the main XChart repo under your account?

**Comment by dluzzon** [comment]
thanks.
now managed to create it.

I thought fork is only for creating new version,.. thanks.
