### ISSUE TITLE
stick chart - how to increase the distance between the sticks

### ISSUE THREAD

**Issue by dluzzon** [timmolter/XChart#139]
Hi, is there a way to control the distance between the stick so they will not be so close one to each other.
if not supported yet, can you point to the class that should be enhanced.

Thanks.

**Comment by timmolter** [comment]
Stick charts are only for `Chart_Category` type charts. for `Chart_Category` the number of sticks is exactly the number of categories you provide. The sticks are spaced evenly across the X-Axis. So changing the spacing doesn't make sense. 

If you mean "drop out some sticks", then you probably would want to be able to create a `Chart_XY` chart type that supports the `stick` series type. If that's what you want, you can look at the `Chart_XY` code and did in from there.

**Comment by dluzzon** [comment]
I'm using Chart_category.
attached sample that explain the question
![stick_chart](https://cloud.githubusercontent.com/assets/13005759/13088566/6ac013e2-d4f5-11e5-9c13-3a249837e275.png)

**Comment by timmolter** [comment]
can you send me the code to produce that chart? Just paste it here in a message...

**Comment by dluzzon** [comment]
בס"ד

 

Hi, 

Here is the code, I have past the items related to this chart. As it is written on few files.

 

1.        

      public void buildSummaryData()

      {

            RefLocal savingPercentageChartLcl = LocalDataFactory.getLocalByKey(MRTConstants.charts.SAVING_PRECENTAGE_SERIES);

            RefLocal volatilityPercentageChartLcl = LocalDataFactory.getLocalByKey(MRTConstants.charts.VOLATILITY_PRECENTAGE_SERIES);

            RefLocal paymentPercentageChartLcl = LocalDataFactory.getLocalByKey(MRTConstants.charts.PAYMENT_PRECENTAGE_SERIES);

 

            double paymentOverLoan = 0;

            double paymentPercentageOverLoan = 0;

            

            Map<Integer, MrtResultsSummary> mrtResultsSummaryMapOut = mrtSummaryOut.getMrtTotalResaultsMap();

            

            MrtResultsSummary mrtResultsSummary = null;

            int listSize = mrtResultsSummaryMapOut.size();

          xSummaryData = new ArrayList<String>(listSize);

          ySavingData = new ArrayList<Double>(listSize);

          volatilityYData = new ArrayList<Double>(listSize);

          paymentPercentageYData = new ArrayList<Double>(listSize);

          

            for (Map.Entry<Integer, MrtResultsSummary> mrtResultsSummaryEntry : mrtResultsSummaryMapOut.entrySet())

            {

                  MrtPackage mrtPackage = mrtMrtManagertPackagesMap.get(mrtResultsSummaryEntry.getKey().shortValue());

                  mrtResultsSummary = mrtResultsSummaryEntry.getValue();

                  xSummaryData.add(mrtPackage.getPackageTitle());

                  ySavingData.add(mrtResultsSummary.getCompareSavingAmount());

                  volatilityYData.add(mrtResultsSummary.getMovementPercentage());

                  paymentOverLoan = mrtResultsSummary.getTotalPayment() - mrtResultsSummary.getPackLoanAmount();

                  paymentPercentageOverLoan = ((paymentOverLoan / mrtResultsSummary.getPackLoanAmount()) * 100);

                  paymentPercentageYData.add(MRTUtil.roundTwoDecimals(paymentPercentageOverLoan, MRTConstants.NUM_FORMAT));

            }

            

            

            

            Series_Category savingPercentageSeries = stickVolatilityChart.getChart().addSeries(CommonUtil.getLocalValue(savingPercentageChartLcl), xSummaryData, savingPercentageYData);

            stickVolatilityChart.setSeriesStyle(savingPercentageSeries);

            Series_Category paymentPercentageSeries = stickVolatilityChart.getChart().addSeries(CommonUtil.getLocalValue(paymentPercentageChartLcl), xSummaryData, paymentPercentageYData);

            stickVolatilityChart.setSeriesStyle(paymentPercentageSeries);

            Series_Category volatilitySeries = stickVolatilityChart.getChart().addSeries(CommonUtil.getLocalValue(volatilityPercentageChartLcl), xSummaryData, volatilityYData);

            stickVolatilityChart.setSeriesStyle(volatilitySeries);

 

      }

 

2.       Attached stick chart class

a.       super.setChartStyle(chart);  used on line 52 having this code:

   protected void setChartStyle(Chart<?, ?> chart)

    {

       chart.getStyler().setChartBackgroundColor(ChartColor.getAWTColor(ChartColor.WHITE));

       chart.getStyler().setChartFontColor(ChartColor.getAWTColor(ChartColor.DODGE_BLUE_4));

       chart.getStyler().setPlotBorderColor(ChartColor.getAWTColor(ChartColor.DODGE_BLUE_4));

    }

b.      writeImage – is called in order to write the image as png

 

if need more clarification please let me know.

 

Best Regards,

Danny.

**Comment by dluzzon** [comment]
adding here item 2 from above. not sure if attachment provided from mail.
package home.charts;


import java.io.IOException;

import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.BitmapEncoder.BitmapFormat;
import org.knowm.xchart.ChartBuilder_Category;
import org.knowm.xchart.Chart_Category;
import org.knowm.xchart.Series_Category.ChartCategorySeriesRenderStyle;
import org.knowm.xchart.internal.Series_AxesChart;
import org.knowm.xchart.internal.style.Styler.LegendPosition;

import home.charts.base.ChartBase;
import home.charts.internal.ChartColor;

public class VolatilityChartHandler extends ChartBase {
	
	private Chart_Category chart = createChart();

	
	public VolatilityChartHandler() {
		super();
	}
	
	@Override
	public Chart_Category createChart()
	{		
	    // Create Chart
		chart = new ChartBuilder_Category().width(getWidth()).height(getHeight()).build();
	
	    // Customize Chart
	    chart.getStyler().setLegendPosition(LegendPosition.OutsideE);
	    
	    return chart;
	}
	  
	
	@Override
	public void setSeriesStyle(Series_AxesChart series) 
	{
//		series.setMarker(SeriesMarkers.NONE);
//		series.setLineStyle(SeriesLines.SOLID);
	}
	
	
	public void writeImage(BitmapFormat imageType) throws IOException
	{
		chart.setTitle(getChartTitle());
		super.setChartStyle(chart);
		chart.getStyler().setDefaultSeriesRenderStyle(ChartCategorySeriesRenderStyle.Stick);
		chart.getStyler().setPlotBackgroundColor(ChartColor.getAWTColor(ChartColor.SEE_SHEL_1));
		chart.getStyler().setLegendBorderColor(ChartColor.getAWTColor(ChartColor.SAGI_SALMON));
	    chart.getStyler().setPlotGridLinesColor(ChartColor.getAWTColor(ChartColor.SAGI_SALMON));
		chart.getStyler().setAxisTickLabelsColor(ChartColor.getAWTColor(ChartColor.DODGE_BLUE_4));
		chart.getStyler().setAxisTickMarksColor(ChartColor.getAWTColor(ChartColor.DODGE_BLUE_4));
		chart.getStyler().setBarsOverlapped(false);
		chart.getStyler().setPlotGridVerticalLinesVisible(false);
		BitmapEncoder.saveBitmapWithDPI(chart, getFullChartPath().toString(), imageType, 300);
	}

	@Override
	protected Chart_Category getChart() {
		
		return chart;
	}
		


    
}

**Comment by joshafest** [comment]
is this issue closed?
or any bounty

**Comment by timmolter** [comment]
I'm going to fix this issue soon.

**Comment by dluzzon** [comment]
Great, appreciate.

**Comment by timmolter** [comment]
Done see latest snapshots. Also see class `TestForIssue139`.

    public class TestForIssue139 {
    
      public static void main(String[] args) {
    
        int[] x = new int[] { 0, 1, 2, 3, 4 };
        int[] a = new int[] { 1, 3, 1, 2, 1 };
        int[] b = new int[] { 2, 1, 1, 2, 2 };
        int[] c = new int[] { 1, 1, 2, 3, 3 };
    
        Chart_Category chart = new ChartBuilder_Category().width(640).height(480).build();
    
        chart.getStyler().setLegendVisible(false);
        chart.getStyler().setDefaultSeriesRenderStyle(ChartCategorySeriesRenderStyle.Stick);
        // chart.getStyler().setBarsOverlapped(true);
        chart.getStyler().setAvailableSpaceFill(.25);
    
        chart.addSeries("A", x, a);
        chart.addSeries("B", x, b);
        chart.addSeries("C", x, c);
    
        new SwingWrapper(chart).displayChart();
      }
    
    }

**Comment by dluzzon** [comment]
working perfect!

**Comment by timmolter** [comment]
try V3.0.2 now.

**Comment by dluzzon** [comment]
I have used v3.0.3, it was ok. and your testSample was helpful.

**Comment by timmolter** [comment]
3.0.3 doesn't exist yet. Only 3.0.3-SNAPSHOT. I mean the official 3.0.2 release on Maven Central supports this bug fix.
