### ISSUE TITLE
Pie chart annotation

### ISSUE THREAD

**Issue by jourquin** [timmolter/XChart#144]
Thank you very much for this interesting piece of work. The API is very simple and it's easy to obtain the wanted chart.

I have some pie charts with 15+ slices, some of them being rather small (2% or so). The annotation is not displayed for these slices. Is there a way to force the display of all annotations ? I would like to avoid the display of the legend as the list of labels is long and  the legend box becomes larger than the size of the XChartPanel (see example).
![piechart](https://cloud.githubusercontent.com/assets/10631047/13502935/53620744-e16d-11e5-8c0e-8f2b811bfcf5.png)

How to reproduce ? just replace chart.addSeries("Pennies", **100**); by chart.addSeries("Pennies", **10**); in PieChart01.java. The annotation for the smaller "Pennies" slice is not dispalyed anymore.

**Comment by billyshea** [comment]
It would probably make sense to have a box pop up whereever labels are hidden telling you what data values are too tiny to see.

**Comment by jourquin** [comment]
Thank you for your answer. i'll have a look to this. In the meantime, I've added the following code to Chart_Pie.java:

_boolean displayAllAnnotations = false;
public boolean isDisplayAllAnnotations() {
	return displayAllAnnotations;
}
public  void setDisplayAllAnnotations(boolean displayAllAnnotations) {
	this.displayAllAnnotations = displayAllAnnotations;
}_


and the following code in PlotContent_Pie.java, just before _if (annotationWillFit)  {...}_ in the paint(...) method.

_// Force the display of all annotations ?
if  ( ((Chart_Pie) chart).isDisplayAllAnnotations()) {
	annotationWillFit=true;
}_

Thus, something like:
_Chart Pie chart = new ChartBuilder_Pie()......build();
chart.setDisplayAllAnnotations(true);_

Forces the display of all annotations. 

Maybe you could put this in the code tree?

**Comment by timmolter** [comment]
What does the above chart look like when you show all annotations? I guess completely cluttered with overlapped labels?

**Comment by jourquin** [comment]
Yes, you are obviously right, but the above graph is some kind of "worst case", and I don't know if there is somewhere a library that handles this nicely.  It is however possible to obtain nice graphs such as this one, inspired from your PieChart03 example:

![piechart03](https://cloud.githubusercontent.com/assets/10631047/13562256/d4d5812c-e436-11e5-816c-b5e007372894.png)

In order to obtain this, in addition to the use of chart.setDisplayAllAnnotations(true), the order in which the series are added has also an importance:

   _chart.addSeries("Munich", 54);
    chart.addSeries("Prague", 2);
    chart.addSeries("Berlin", 29);
    chart.addSeries("Dresden", 3);
    chart.addSeries("Hamburg", 22);
    chart.addSeries("Brussels", 4);
    chart.addSeries("Paris", 20);
    chart.addSeries("London", 5);
    chart.addSeries("Madrid", 18);
    chart.addSeries("Roma", 6);
    chart.addSeries("Copenhagen", 16);
    chart.addSeries("Moscow", 7);
    chart.addSeries("Tokyo", 15);
    chart.addSeries("Lyon", 8);
    chart.addSeries("Milano", _12);_

A you can see, I started with the biggest slice, following by the smallest, then the second largest one, the second smallest...

**Comment by timmolter** [comment]
Thanks, I'll probably just add a style method so the end user can pick it themselves.

**Comment by jourquin** [comment]
Or in series. java ? This would allow to render the annotations in a more flexible way, similarly to setShowInLegend(...) for instance. The user could decide to display the annotations for series with a value larger than a threshold...

**Comment by jourquin** [comment]
Practically:

**in series.java**

    public  enum AnnotationStyle {
	ifFits, never, always
    }

    public AnnotationStyle getAnnotationStyle() {
	return annotationStyle;
    }

    public void setAnnotationStyle(AnnotationStyle annotationStyle) {
	this.annotationStyle = annotationStyle;
    }


**in PlotContent_Pie:**

    if (series.getAnnotationStyle() == AnnotationStyle.never) {
    	  annotationWillFit = false;
      } else {
    	  if (series.getAnnotationStyle() == AnnotationStyle.always) {
    		  annotationWillFit = true;
    	  }
      }

**Example**

   // Series : 
    // always display annotation if value >= 15
    // never display annotation if value < 5
    // display other annotations if fit without clutering (default) 
    
    chart.addSeries("Munich", 54).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Prague", 2).setAnnotationStyle(AnnotationStyle.never);
    chart.addSeries("Berlin", 29).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Dresden", 3).setAnnotationStyle(AnnotationStyle.never);
    chart.addSeries("Hamburg", 22).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Brussels", 4).setAnnotationStyle(AnnotationStyle.never);
    chart.addSeries("Paris", 20).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("London", 5);
    chart.addSeries("Madrid", 18).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Roma", 6);
    chart.addSeries("Copenhagen", 16).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Moscow", 7);
    chart.addSeries("Tokyo", 15).setAnnotationStyle(AnnotationStyle.always);
    chart.addSeries("Lyon", 8);
    chart.addSeries("Milano", 12);

**Comment by timmolter** [comment]
I added a global style to force draw all. See latest snapshot jar.

**Comment by jourquin** [comment]
Thanks for this. I’ve just compiled the 3.0.5 snapshot, and I indeed found the new setDrawAllAnnotations method.

Maybe I missed something, but it seems that the annotations are not displayed anymore in pie charts. I’ve tested PieChart03 of the demo, and no annotation is displayed.

Note that I had implemented a variant that allows to chose, for each slice, how it will be displayed. The code is attached, and my modifications are marked by “BAJ” labels.

In short, in Series, I’ve added a

public enum AnnotationStyle {
  ifFits, never, always
}

For instance, one can force the display all the labels that corresponds to values larger than 1%:

// The “labels” and “pct” vectors contain the labels and values (percentages) of the series
for (int i = 0; i < pct.length; i++) {
                AnnotationStyle style = AnnotationStyle.ifFits;
                if (pct[i] >= 0.01) style = AnnotationStyle.always;
                chart.addSeries(labels[index].elementAt(i), pct[i]).setAnnotationStyle(style);
}

This solution is even more flexible than the setDrawAllAnnotations approach.

Best regards,

Bart

De : Tim Molter <notifications@github.com>
Répondre à : timmolter/XChart <reply@reply.github.com>
Date : dimanche 12 juin 2016 17:27
À : timmolter/XChart <XChart@noreply.github.com>
Cc : Bart Jourquin <bart.jourquin@uclouvain.be>, Author <author@noreply.github.com>
Objet : Re: [timmolter/XChart] Pie chart annotation (#144)


I added a global style to force draw all. See latest snapshot jar.

**Comment by jourquin** [comment]
Thanks for this. I’ve just compiled the 3.0.5 snapshot, and I indeed found the new setDrawAllAnnotations method.
 
Maybe I missed something, but it seems that the annotations are not displayed anymore in pie charts. I’ve tested PieChart03 of the demo, and no annotation is displayed.
 
Note that I had implemented a variant that allows to chose, for each slice, how it will be displayed. The code is attached, and my modifications are marked by “BAJ” labels.
 
In short, in Series, I’ve added a
 
public enum AnnotationStyle {
  ifFits, never, always
}   
 
For instance, one can force the display all the labels that corresponds to values larger than 1%:
 
// The “labels” and “pct” vectors contain the labels and values (percentages) of the series
for (int i = 0; i < pct.length; i++) {
                AnnotationStyle style = AnnotationStyle.ifFits;
                if (pct[i] >= 0.01) style = AnnotationStyle.always;
                chart.addSeries(labels[index].elementAt(i), pct[i]).setAnnotationStyle(style);
}
 
This solution is even more flexible than the setDrawAllAnnotations approach.
 
Best regards,
 
Bart
[knowm.zip](https://github.com/timmolter/XChart/files/311452/knowm.zip)

**Comment by timmolter** [comment]
Whoops! Thanks for telling me it was indeed not working. I just pushed a fix for it. I'll save your series annotation style for a different rainy day. Thanks!

**Comment by jourquin** [comment]
Thanks! It works indeed now.

For your convenience, I've attached a small zip file with the series annotations style changes in the code of the latest 3.1.1 branch. We have a lot of rainy days here in Belgium :-)

[knowm.zip](https://github.com/timmolter/XChart/files/313257/knowm.zip)
