### ISSUE TITLE
Y-axis labels do not line up

### ISSUE THREAD

**Issue by PRKrebs** [timmolter/XChart#150]
On a simple bar chart, the x-axis label are not centered under the corresponding bars, but slightly offset to the left. This offset start with 0 and increases with every bar.

**Comment by timmolter** [comment]
It looks fine to me. What version are you using?

<img width="700" alt="screen shot 2016-04-26 at 9 47 22 am" src="https://cloud.githubusercontent.com/assets/738972/14810584/eb02847a-0b93-11e6-8f7b-ff44d79ac889.png">

**Comment by PRKrebs** [comment]
The last value 'GV' is out by half a bar width. This is version 3.0.3.

![chart](https://cloud.githubusercontent.com/assets/18668625/14847666/2ce9cfc8-0cad-11e6-8dd6-1cbf55e2a059.jpg)

**Comment by timmolter** [comment]
Could you post the code to make that chart? then I can take a better look.

**Comment by timmolter** [comment]
Nevermind. I was able to create it myself...

**Comment by timmolter** [comment]
Fixed. See latest snapshot jar. I'll do a 3.0.4 release soon.

**Comment by timmolter** [comment]
FYI 3.0.4 released.
