### ISSUE TITLE
Add series with same label

### ISSUE THREAD

**Issue by thorstenwagner** [timmolter/XChart#151]
I would like to add multiple series with the same label to a chart. In my case the label represents a class inside of trajectories (made of (x,y) positions). The first 100 steps are of class 'A', the second 100 steps of class 'B' and the last 100 steps are of class 'A' again.

However, at the moment it seems to me that all classes have to have unique labels.

**Comment by timmolter** [comment]
One thing you could try is to create a single series and put all the sub series data together separated by a NaN value.

**Comment by timmolter** [comment]
Here's exactly how to do it:

```
  public static void main(String[] args) {

    // Create Chart
    XYChart chart = new XYChartBuilder().width(600).height(400).build();

    // Customize Chart

    // Series
    double[] xData1 = new double[] { 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14, 15 };
    double[] yData1 = new double[] { 106, 44, 26, 10, 11, 19, 25, Double.NaN, 30, 21, 36, 32, 30 };
    double[] xData2 = new double[] { 6, 7, 8, 9, 10, 11 };
    double[] yData2 = new double[] { 25, 54, 43, 56, 33, 30 };

    chart.addSeries("A", xData1, yData1);
    chart.addSeries("B", xData2, yData2);

    new SwingWrapper<XYChart>(chart).displayChart();
  }
```

<img width="600" alt="screen shot 2016-06-13 at 10 35 57 am" src="https://cloud.githubusercontent.com/assets/738972/16001514/b5495c20-3152-11e6-90c6-186e4131cac9.png">

**Comment by thorstenwagner** [comment]
Yes! Great! Thank you very much!
