### ISSUE TITLE
GUI window not opening in ubuntu

### ISSUE THREAD

**Issue by julian-ramos** [timmolter/XChart#154]
Hi there,

I have been trying to use XChart but the GUI window does not show up. It appears on the unity panel and appears to be running but the window itself is not shown. For example, running the demo from the terminal does not show any errors or warning it simply does not show up. 

Using ubuntu 14.10 64 bits

Thanks,

**Comment by julian-ramos** [comment]
As an update, after testing many different things what ended up working was to switch from gnome to KDE. For whatever reason now the window is visible.

**Comment by timmolter** [comment]
Weird. What JRE are you running? You could try Java 8:


```
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get -y install oracle-java8-installer
java -version
```

**Comment by timmolter** [comment]
FYI, I just fired up Ubuntu 16.04 stock with Oracle Java 8, and the XChart demo worked fine. I'm not sure what issue you were having,

**Comment by julian-ramos** [comment]
This occurred on Ubuntu 14.10. I had java 8. I actually found out the same issue with other GUI's like the one for weka. All of them started to show properly on the screen after installing kde-desktop.
