### ISSUE TITLE
Non-modal windows

### ISSUE THREAD

**Issue by thorstenwagner** [timmolter/XChart#156]
Hi,

I'm using xchart (2.6.1) is some of my ImageJ plugins. The plot is shown by
```java
new SwingWrapper(charts, numRows, numCols).displayChartMatrix();
``` 
However, as soon I close the plot imagej closes as well. How can I open non-model charts?

Regards,
Thorsten

**Comment by timmolter** [comment]
Can you try 3.1.0? 

`SwingWrapper` is meant as a quick and dirty way to pop up a plot. What you can do create a `JPanel` with the chart, and integrate it into your app however you want:

      JPanel chartPanel = new XChartPanel(chart);
