### ISSUE TITLE
Feature Request: enabling and disabling series

### ISSUE THREAD

**Issue by utwbu** [timmolter/XChart#158]
I am developing an application which shows a lot of series in an XYChart. To simplify reading the diagrams, it is possible to enable and disable series. A disabled series is invisible.

Currently I have to remove / add the series from the chart. In case all series are removed, I add a dummy series to keep the x-axis data type Date. 

A flag at the series objects, which just skips the series from being painted and being visible in the legend would help me a lot.

Would it be possible to implement this?

**Comment by utwbu** [comment]
I found a way to enable and disables series:

` XYSeries xySeries = logChart.getSeriesMap().get(seriesName);`
`xySeries.setLineStyle(SeriesLines.NONE);`

**Comment by timmolter** [comment]
Do it remove it from the legend as well?

**Comment by utwbu** [comment]
The name of the series is still visible in the legend. The line in front of the name disappears as well.

**Comment by timmolter** [comment]
I added this feature. Please check it out if you are interested. Just call `series.setEnabled()`.

**Comment by utwbu** [comment]
Thank you for adding this features! I tested it with version 3.3.0, but it seems there is a small problem: When all series are disabled, the thread performing the paint method gets stuck in an endless loop.

the following example produces this isse as well (In my application this happens when the user disabled all series.):

```
    public static void main(String[] args) throws Exception {

        double[] xData = new double[] { 0.0, 1.0, 2.0 };
        double[] yData = new double[] { 2.0, 1.0, 0.0 };

        XYChart chart = new XYChart(500, 200);
        XYSeries xySeries = chart.addSeries("Sample Chart", xData, yData);
        xySeries.setEnabled(false);

        new SwingWrapper(chart).displayChart();
    }
```

The loop is located in AxisTickCalculator_Number line 107:

```
        while (significand >= 10 || significand == Double.NEGATIVE_INFINITY) {
          significand /= 10.0;
          exponent++;
        }
```
The variable 'significand' has the value 'Infinity'.

**Comment by timmolter** [comment]
please test

**Comment by utwbu** [comment]
Works great! 

Thank you very much!
