### ISSUE TITLE
server side usage

### ISSUE THREAD

**Issue by cosminbasca** [timmolter/XChart#161]
can XChart be used without a UI? output directly to png or svg ? Thanks!

**Comment by timmolter** [comment]
Yes. Se here:<https://github.com/timmolter/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/Example1.java>.

**Comment by cosminbasca** [comment]
Hi @timmolter, thanks for the quick reply. A late night bug (which resulted in a null series) gave out a not so clear error message which miss-lead me in a different direction. All works fine now! Perhaps as an improvement: a more informative error message when either axis arrays are null would help. Thanks again!

**Comment by timmolter** [comment]
Do you still have a stack trace that I could see? Then I can add a better message.
