### ISSUE TITLE
Same package protected methods calls

### ISSUE THREAD

**Issue by dmitrycm** [timmolter/XChart#165]
Hi!

Sometimes it is needed to override something. In XChart the "accessing protected from the same package" rule is often used. As a result, the local workaround solutions don't look good. 
That is going about functionality that is not supposed to be a part of the lib.

Thanks

**Comment by timmolter** [comment]
Some things are `protected` if it's not meant to be overridden. What exactly would you like to override?

**Comment by dmitrycm** [comment]
> if it's not meant to be overridden.

`final`?

In my case I inherit from Series_Markers to make a series for my own chart class. I need to rewrite `calculateMinMax` but I can not because xMin and xMax do not have setters.
