### ISSUE TITLE
CategorySeriesRenderStyle.Line bug

### ISSUE THREAD

**Issue by odporkka** [timmolter/XChart#167]
Hey!

I got CategoryChart with years in x-axis and some data in y-axis. Y-axis data can be negative or null. When I draw this as CategorySeriesRenderStyle.Bar which is default it draws nicely showing negative values and leaving empty spaces whenever there is null. However when I change charts default render style with `.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.Line);` it doesn't leave empty spaces when there is null value in y-axis data, but draws everything at the start of the chart leaving empty space to the wrong years at the end.

I also tried setting each series render style individually with `.setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Line` and then null values draw just fine. But now all negative values are drawn as zeroes. It scales chart fine but all the lines just go to zero when they should go to negative value.

I've checked imported data with `.getSeriesMap()` and it is correct showing negative values and nulls in correct places. Overlapping is set true. Also I'm using GGPlot2 -theme but this happens with default one too.

This seems to be a bug when setting render style to `CategorySeriesRenderStyle.Line`.

Any workaround ideas also appreciated, since I am on a tight schedule.

Thanks in advance!

**Comment by timmolter** [comment]
Please post an example chart class that shows the problem and I'll try to fix it and push a new release. You can use a class in <https://github.com/timmolter/XChart/tree/develop/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/bar> and modify it. Thanks!

**Comment by odporkka** [comment]
Here ya go! Any estimate when this would be fixed? :)

```
public class BarChart01 implements ExampleChart<CategoryChart> {

	public static void main(String[] args) {

		ExampleChart<CategoryChart> exampleChart = new BarChart01();
		CategoryChart chart = exampleChart.getChart();
		CategoryChart chart2 = ((BarChart01) exampleChart).getChart2();
		new SwingWrapper<CategoryChart>(chart).displayChart();
		new SwingWrapper<CategoryChart>(chart2).displayChart();
	}

	@Override
	public CategoryChart getChart() {

		// Create Chart
		CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("CategorySeriesRenderStyle-bug")
				.xAxisTitle("Year").yAxisTitle("Data").build();

		// Customize Chart
		chart.getStyler().setLegendVisible(false);
		chart.getStyler().setHasAnnotations(true);
		chart.getStyler().setOverlapped(true);

		// This is the setting that causes troubles. When setting this to .Bar
		// it works just fine. Draws negative values but doesn't leave blank to
		// nulls.
		chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.Line);

		// Series
		String[] years = new String[] { "2000", "2001", "2002", "2003", "2004" };
		chart.addSeries("data 1", Arrays.asList(years),
				Arrays.asList(new Double[] { 100.0, 110.0, 120.0, 130.0, 140.0 }));
		chart.addSeries("data 2", Arrays.asList(years), Arrays.asList(new Double[] { 50.0, 60.0, 70.0, null, 90.0 }));
		chart.addSeries("data 3", Arrays.asList(years),
				Arrays.asList(new Double[] { -50.0, -60.0, -70.0, null, -90.0 }));
		chart.addSeries("data 4", Arrays.asList(years),
				Arrays.asList(new Double[] { -100.0, -110.0, -120.0, -130.0, -140.0 }));

		return chart;
	}

	public CategoryChart getChart2() {

		// Create Chart
		CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("CategorySeriesRenderStyle-bug")
				.xAxisTitle("Year").yAxisTitle("Data").build();

		// Customize Chart
		chart.getStyler().setLegendVisible(false);
		chart.getStyler().setHasAnnotations(true);
		chart.getStyler().setOverlapped(true);

		// Series
		String[] years = new String[] { "2000", "2001", "2002", "2003", "2004" };
		CategorySeries data1 = chart.addSeries("data 1", Arrays.asList(years),
				Arrays.asList(new Double[] { 100.0, 110.0, 120.0, 130.0, 140.0 }));
		CategorySeries data2 = chart.addSeries("data 2", Arrays.asList(years),
				Arrays.asList(new Double[] { 50.0, 60.0, 70.0, null, 90.0 }));
		CategorySeries data3 = chart.addSeries("data 3", Arrays.asList(years),
				Arrays.asList(new Double[] { -50.0, -60.0, -70.0, null, -90.0 }));
		CategorySeries data4 = chart.addSeries("data 4", Arrays.asList(years),
				Arrays.asList(new Double[] { -100.0, -110.0, -120.0, -130.0, -140.0 }));

		// Now rendering is set individually to line per series. Draws nulls but
		// all negatives are drawn as zero.
		data1.setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Line);
		data2.setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Line);
		data3.setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Line);
		data4.setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Line);
		return chart;
	}
}
```

**Comment by timmolter** [comment]
Thanks, I see two bugs. I'm working on it now.

**Comment by timmolter** [comment]
Fixed. Pushing 3.2.2 to Maven Central now. You might need to wait an hour. 

<img width="500" alt="screen shot 2016-11-24 at 5 49 02 pm" src="https://cloud.githubusercontent.com/assets/738972/20605991/76343efe-b26e-11e6-980f-ae30aad8d18a.png">

**Comment by odporkka** [comment]
Wow that was fast! Thank you very much :)
