### ISSUE TITLE
Grouped bar charts?

### ISSUE THREAD

**Issue by spyhunter99** [timmolter/XChart#169]
Wondering if this is possible out of the box. I was previously using jfreechart to do this and due to license compatibility issues, I have to switch. I have a use case where by I have a bar chart with a number of x axis "groups", each with their own unique x values and corresponding bars. All bars are on the same Y scale. In this case, i'm tracking performance of a web service, whereby the performance is broken down by whatever the 'action' was on the service (get, put, post, method1, etc)

Here's a screener or what I had previously. Obviously, this is oriented horizontally, which isn't currently possible with xcharts, no biggie.

![image_average_response_time_by_service_by_method](https://cloud.githubusercontent.com/assets/1975321/21083312/b0d6dc74-bfbb-11e6-9ddf-4dd92881248f.png)

**Comment by timmolter** [comment]
Sorry, that's not possible. :(
