### ISSUE TITLE
Settting major/minor tick positions?

### ISSUE THREAD

**Issue by io7m** [timmolter/XChart#173]
Hello. Apologies if this is answered in the example code or JavaDoc - I've not been able to find anything in either of those.

How do I control where major and minor tick marks are placed?

For example, I have a graph that has a `Date` typed X axis and a `Long` typed Y axis. For the X axis, I'd like to be able to place major tick marks on 12 hour boundaries and minor tick marks on hour boundaries. For the Y axis, I'd like to place major tick marks on multiples of 100000, and minor tick marks on multiples of 10000.

The only things I can find in the API are the methods on `XYStyler` type such as `setYAxisTickMarkSpacingHint`, but it's not clear how to use them. What units are they specified in? It just takes an `int` parameter... Am I even looking at the right methods?

**Comment by timmolter** [comment]
`setYAxisTickMarkSpacingHint` is in units of pixels. I'll update the javadoc on that method. As far as specifying what you're looking for, it's not possible. You could attempt it using `setYAxisTickMarkSpacingHint` and a custom axis formatter perhaps.
