### ISSUE TITLE
Optional sum (total value) in pie charts?

### ISSUE THREAD

**Issue by ekleinod** [timmolter/XChart#174]
This is a feature request (I cannot set the label) for an optional sum (=total value) in pie charts. 

The sum would be the sum of all pie series values. It should be output in the centre of the chart. I think it would be great if it had an own font to choose, i.e. it would result in a API addition for `PieStyler` as follows:

- `isSumVisible` (default: `false`)
- `setSumVisible`
- `getSumFont`
- `setSumFont`

Maybe prefixing with `Pie` like in `isPieSumVisible` etc. would be better for the sake of clarity?

As I cannot upload any images, I uploaded an example to illustrate what I mean to:

[http://www.ekkart.de/downloads/pie_sum.png](http://www.ekkart.de/downloads/pie_sum.png)

**Comment by timmolter** [comment]
You could out it in the title for now.

**Comment by ekleinod** [comment]
I am giving it a shot, please wait with your own implementation :)
