### ISSUE TITLE
File extension when saving vector graphics

### ISSUE THREAD

**Issue by ekleinod** [timmolter/XChart#175]
When using `VectorGraphicsEncoder.saveVectorGraphic` the file extension is always added.

When using `BitmapEncoder.saveBitmap` the file extension is added only if it is not present already.

It would be nice if both methods would behave the same.

Thanks for the great work.

**Comment by timmolter** [comment]
please test

**Comment by ekleinod** [comment]
Tested, works like a charm, thanks.

I tested the `addFileExtension` method using JUnit as well as the output using my application.

JUnit-Test in branch feature/test of https://github.com/ekleinod/XChart

**Comment by timmolter** [comment]
Thank you!
