### ISSUE TITLE
Legend border not resizing after series.setEnabled()

### ISSUE THREAD

**Issue by RNuWM** [timmolter/XChart#180]
Thank you for the incredible package, it is exceptional. 

I have an issue with the recent series.setEnabled() and its interaction with the legend. The border does not dynamically update to properly fit the setEnabled() series. See the attached picture (series names edited out). I am not sure if it is a bug or the result of me not properly updating the legend. 

![legend](https://cloud.githubusercontent.com/assets/28081765/25506824/73eb2fd2-2b5d-11e7-9da3-49c469991154.png)

I have a JPanel containing many XChartPanel’s each containing an XYchart.  I do significant real-time updating on them. Thus far it has always been sufficient to call revalidate() and repaint() on the JPanel to update all of the charts. Do I need to do something different in this scenario to update the state of the legend to match the visible series?

Thanks!

**Comment by timmolter** [comment]
OK, I attempted a fix. Can you try the latest snapshot jar please?

**Comment by RNuWM** [comment]
This fixed the issue in all cases that I deal with. I will look for it in the next official release.

Thanks so much!

**Comment by timmolter** [comment]
Thanks for testing! I'll push a new release soon.
