### ISSUE TITLE
setXAxisMin(0.0) and setYAxisMin(0.0) not working properly?

### ISSUE THREAD

**Issue by Perneel** [timmolter/XChart#181]
I'm creating a XYChart. I have set the following:

    chart.getStyler().setXAxisMin(0.0);
    chart.getStyler().setYAxisMin(0.0);

This is the result:

![image](https://cloud.githubusercontent.com/assets/4124110/25534718/fe58f2d0-2c34-11e7-9096-267f5277477d.png)

Shouldn't be the point at 0.0 in the lower left corner? Or am I missing a padding or margin somewhere?

**Comment by timmolter** [comment]
Can you paste here a full Java class producing the above plot please?

**Comment by Perneel** [comment]
As requested:
               
               // Create Chart
                XYChart chart = new XYChartBuilder()
                        .width(500)
                        .height(350)
                        .theme(ChartTheme.Matlab)
                        .build();

                // Series
                .....
                chart.addSeries("Serie1", xData1, yData1);
                chart.addSeries("Serie2", xData2, yData2);
                XYSeries vertical = chart.addSeries("vertical", new double[]{5, 5}, new double[]{0, 10});
                vertical.setShowInLegend(false);
                vertical.setXYSeriesRenderStyle(XYSeriesRenderStyle.Line);
                vertical.setLineStyle(SeriesLines.SOLID);
                XYSeries horizontal = chart.addSeries("horizontal", new double[]{0, 10}, new double[]{5, 5});
                horizontal.setShowInLegend(false);
                horizontal.setXYSeriesRenderStyle(XYSeriesRenderStyle.Line);
                horizontal.setLineStyle(SeriesLines.SOLID);

                // Customize Chart
                Marker[] markers = {SeriesMarkers.SQUARE, SeriesMarkers.SQUARE, SeriesMarkers.DIAMOND, SeriesMarkers.DIAMOND};
                Color[] colors = {Color.GRAY, Color.BLUE, Color.RED, Color.RED};

                chart.getStyler().setDefaultSeriesRenderStyle(XYSeriesRenderStyle.Scatter);
                chart.getStyler().setLegendPosition(LegendPosition.OutsideE);
                chart.getStyler().setMarkerSize(5);
                chart.getStyler().setAxisTicksVisible(false);
                chart.getStyler().setXAxisMin(0.0);
                chart.getStyler().setYAxisMin(0.0);
                chart.getStyler().setSeriesMarkers(markers);
                chart.getStyler().setSeriesColors(colors);
                chart.getStyler().setPlotGridLinesVisible(false);

**Comment by timmolter** [comment]
It's working fine I believe. First without min/max, second is with.

<img width="1001" alt="screen shot 2017-05-01 at 9 54 28 am" src="https://cloud.githubusercontent.com/assets/738972/25575102/3e708f88-2e54-11e7-9679-c7b248ddcf82.png">

**Comment by timmolter** [comment]
```
public class TestForIssue181 {

  public static void main(String[] args) {

    // Create Chart
    XYChart chart = new XYChartBuilder()
        .width(500)
        .height(350)
        .theme(Styler.ChartTheme.Matlab)
        .build();

    // Series
    List<Double> xData = new LinkedList<Double>();
    List<Double> yData = new LinkedList<Double>();

    Random random = new Random();
    int size = 1000;
    for (int i = 0; i < size; i++) {
      xData.add(5 * random.nextGaussian());
      yData.add(5 * random.nextGaussian());
    }
    chart.addSeries("Gaussian Blob", xData, yData);

    XYSeries vertical = chart.addSeries("vertical", new double[]{5, 5}, new double[]{0, 10});
    vertical.setShowInLegend(false);
    vertical.setXYSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);
    vertical.setLineStyle(SeriesLines.SOLID);
    XYSeries horizontal = chart.addSeries("horizontal", new double[]{0, 10}, new double[]{5, 5});
    horizontal.setShowInLegend(false);
    horizontal.setXYSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);
    horizontal.setLineStyle(SeriesLines.SOLID);

    // Customize Chart
    Marker[] markers = {SeriesMarkers.SQUARE, SeriesMarkers.SQUARE, SeriesMarkers.DIAMOND, SeriesMarkers.DIAMOND};
    Color[] colors = {Color.GRAY, Color.BLUE, Color.RED, Color.RED};

    chart.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Scatter);
    chart.getStyler().setLegendPosition(Styler.LegendPosition.OutsideE);
    chart.getStyler().setMarkerSize(5);
    chart.getStyler().setAxisTicksVisible(false);
    chart.getStyler().setXAxisMin(0.0);
    chart.getStyler().setYAxisMin(0.0);
    chart.getStyler().setSeriesMarkers(markers);
    chart.getStyler().setSeriesColors(colors);
    chart.getStyler().setPlotGridLinesVisible(false);

    new SwingWrapper<XYChart>(chart).displayChart();
  }
}
```

**Comment by Perneel** [comment]
Hm it's still not totally clear to me, I took the example of your screenshot with the min/max applied:

![image](https://cloud.githubusercontent.com/assets/4124110/25743500/0475f0a4-3195-11e7-8a98-4b6107940ded.png)

Shouldn't the light blue lines be the axis? Or am I missing something? :)

**Comment by timmolter** [comment]
Yes, that's 0,0. Set `chart.getStyler().setAxisTicksVisible(true);` and you will see.

**Comment by Perneel** [comment]
Aha I see... is there a possibility to show the axis actually on the 0.0 point?

**Comment by timmolter** [comment]
try `chart.getStyler().setPlotContentSize(1.0);`

**Comment by Perneel** [comment]
jep that's what I was looking for, thanks a lot!
