### ISSUE TITLE
CategoryChart with two Bars and one Line 

### ISSUE THREAD

**Issue by fcecchin** [timmolter/XChart#185]
It's not a issue, but a doubt. 
I would like to build a CategoryChart with two, not ovelapping, bars series and one line serie overlapping the bars. I didn't see any example on xchart-demo. Is it possible?

To clarify, I need two series as Bars side-by-side and one serie as Line over the bars. 
Thank you in advance.

Not like this....
![image](https://cloud.githubusercontent.com/assets/4399014/26466581/918a5068-4165-11e7-9655-11f2b08c2791.png)

**Comment by timmolter** [comment]
Sorry, I don't think it's possible. Either all overlapping or not.
