### ISSUE TITLE
Feature request: add text annotations to graphs

### ISSUE THREAD

**Issue by parrt** [timmolter/XChart#190]
XChart looks great. Using for some machine learning stuff. For example:

<img width="793" alt="screen shot 2017-06-15 at 1 56 59 pm" src="https://user-images.githubusercontent.com/178777/27201435-84fc4e8c-51d2-11e7-90b8-ff5484b4e194.png">

What'd I'd like is ability to write text to annotate a graph or add arrows ala matplotlib; e.g.,

![](https://matplotlib.org/_images/annotate_text_arrow.png)

Should I just write to the underlying Swing canvas?

Thanks for the great lib and "howdy" from the ANTLR guy.

**Comment by timmolter** [comment]
Howdy! Yes, you'll have to add it to the Swing Panel manually.

**Comment by parrt** [comment]
Ok, maybe i'll add some functionality and send you a pull request.

**Comment by timmolter** [comment]
Yes, that'd be a welcome addition.

**Comment by Taredel** [comment]
@timmolter 
Has this feature actually been implemented?
Can you please link if so, thanks in advance
