### ISSUE TITLE
Allow top alignment for rotated X axis labels

### ISSUE THREAD

**Issue by mvmn** [timmolter/XChart#193]
Example use-cases: 90-degree rotation of X axis labels with texts of different length.

Current result - all texts are bottom-aligned, which makes it hard for short text labels to be visually associated with graph data:
<img width="1552" alt="screen shot 2017-06-16 at 03 30 16" src="https://user-images.githubusercontent.com/1076779/27223066-a3102b08-5297-11e7-9f13-8849c30e38e0.png">

Expected result:
<img width="1552" alt="screen shot 2017-06-16 at 03 30 10" src="https://user-images.githubusercontent.com/1076779/27223090-bd2c48aa-5297-11e7-84d2-e53455a7b246.png">

The alignment should be configurable (top/center/bottom).

Actually I've implemented this, here's a pull request. I've re-used existing constants for alignment, so Left means Bottom, Right means Top. This can be adjusted if necessary, but works fine already.
https://github.com/timmolter/XChart/pull/191

**Comment by timmolter** [comment]
Thank you!
