### ISSUE TITLE
Allow conversion from rendered X/Y coordinates to chart X/Y coordinates

### ISSUE THREAD

**Issue by paharvey** [timmolter/XChart#195]
I need to be able to take rendered output X/Y coordinates and extract the matching chart data X/Y coordinates. Is that possible? It seems that many methods, eg. Chart.getYAxis() and Axis.getMin() are protected, so I have no means to turn a mouse X/Y coordinate into the data values at that location.

**Comment by timmolter** [comment]
I don't understand what you're asking. What exactly do you want to achieve?

**Comment by paharvey** [comment]
For a given X/Y pixel coordinate in an XYSeries chart, I want to get the value from the X axis and the value(s) from the Y axes. I have not tested, but I'm looking for methods like these on the Chart class.

```
	public double fromPixelX(double x) {
		Rectangle2D bounds = getPlot().getBounds();
		double max = getXAxis().getMax();
		double min = getXAxis().getMin();
		return (x - bounds.getMinX()) / bounds.getWidth() * (max - min) + min;
	}

	public double fromPixelY(int yIndex, double y) {
		Rectangle2D bounds = getPlot().getBounds();
		double max = getYAxis(yIndex).getMax();
		double min = getYAxis(yIndex).getMin();
		return (y - bounds.getMinY()) / bounds.getHeight() * (max - min) + min;
	}

```

My ultimate goal is to allow a user to hover over an XChartPanel, extract the coordinates they are hovering over, and show the results in a status bar at the bottom of my application window.

By the way, I really like what I've seen of your library so far. I am not terribly familiar with Git "pull requests" and such. If I find time to contribute to your library, do you have a preference on how I could contribute?

**Comment by timmolter** [comment]
So you want to show the datapoint x,y datapoint to the user? One option is to enable tooltips:     chart.getStyler().setToolTipsEnabled(true);
See `BarChart07`.

Otherwise if you want to show the pixel coordinates, that you can just do with a mouse listener.

Yes, pull requests is the way to go. Just google on how to do it.

**Comment by paharvey** [comment]
Thanks. The reason I'm not using the Tooltips is:

1. I want the user to be able to point at any datapoint, not just the vertices of my lines
2. I may have a lot of datapoints, with values that can change rapidly, and I'm worried about re-paint performance using the existing Tooltips implementation. It formats all datapoints even though very few (at most one?) may need to be painted. I may test enabling Tooltips only on mouse-over.

Anyway, thanks again for the great library. I'll try to find time to make some contributions, specifically around performance for large data sets.
