### ISSUE TITLE
Text spacing issues in legend

### ISSUE THREAD

**Issue by RNuWM** [timmolter/XChart#200]
I am having text spacing in the legend entries:

![text spacing](https://user-images.githubusercontent.com/28081765/28222807-d646d73c-687d-11e7-8d35-1ad1e3bb63f7.png)

It seems to primarily (maybe only?) come up with the character 'w'.  It almost seems as if an entire space character is being added after the 'w'.  I do not know enough about Java text rendering to understand the issue.  Is the source of this from the drawing of the text done by XChart? Or something I am doing?

This is with version 3.3.1.  The only legend related calls I use are setLegendPosition() and setLegendVisible(). I don't set anything to do with the text other than setting the series name string.

**Comment by timmolter** [comment]
That's very strange. Can you post a test class with a main method that shows that problem? Also, try version 3.4.0.
