### ISSUE TITLE
Feature request: XChart should support turning anti-aliasing off

### ISSUE THREAD

**Issue by jmtilli** [timmolter/XChart#201]
I'm implementing a software for curve fitting where the fitting performance is of utmost importance. Thus, the chart library needs to be as fast as possible. Currently I'm using JFreeChart, but would like to switch to XChart. Unfortunately, XChart made my application 3.9% slower (I had to do few optimizations that were applicable to JFreeChart as well; without those optimizations the application was 15% slower than with JFreeChart). This is slightly over the border of acceptability, and is way over statistical significance limit.

I investigated the issue and found that if I turn anti-aliasing off inside XChart like I do with JFreeChart, the application is now only 0.9% slower than with JFreeChart. This might be considered acceptable, and it is slightly below the statistical significance limit (I used the 95% confidence level).

Unfortunately, after disabling anti-aliasing inside XChart by modifying the code, the title and axis fonts look ugly although the plot itself looks acceptable. I believe this could be fixed perhaps by turning anti-aliasing on only for drawing the text and turning it off for the charts. It also perhaps could be fixed by using bitmap fonts instead of freely scalable fonts. I'm not sure how JFreeChart does it, but the fonts of JFreeChart are not ugly even if anti-aliasing is turned off.

So, XChart should support an option to turn off anti-aliasing, and some way should be found to solve the ugly font problem caused by that.

The way I turned off anti-aliasing was by changing RenderingHints.VALUE_ANTIALIAS_ON into RenderingHints.VALUE_ANTIALIAS_OFF (there's just one occurrence of this in the codebase), but for real production use, some kind of interface needs to be defined to affect the hint.

**Comment by jmtilli** [comment]
Additional tests: the KEY_TEXT_ANTIALIASING appears to be non-functional, so using it does not help. If I turn KEY_ANTIALIASING on only for the duration of rendering the title and axes, and off for rendering anything else, XChart is 1.3% slower than JFreeChart but now the text fonts are pretty. Might be acceptable.

**Comment by timmolter** [comment]
My quick test show that turning anti-aliasing off affects the line rendering as well:

![screen shot 2017-07-18 at 9 07 03 am](https://user-images.githubusercontent.com/738972/28304578-8670c7ea-6b98-11e7-8986-6d061be719ab.png)

Thanks for posting this. I never did a speed comparison with JFreeChart, and I'm surprised XChart does as well as it does since I never really optimized it yet. Let me try a few things and I'll post my findings. 

I'd be interested in running the speed comparison code, so if you'd like to contribute that to the project, I'd be grateful.

**Comment by timmolter** [comment]
It doesn't look like bitmap fonts are supported without some hack.
https://stackoverflow.com/questions/8459481/bitmap-fonts-in-java

**Comment by jmtilli** [comment]
The curve-fitting application can be found from master branch in https://github.com/jmtilli/micronovaxrr -- clone, build with ant and run with "java -jar xrr.jar". Then open measurement xrr003.x00 and layers file xrr003.x00.layers. Go to automatic fit tab, press import, turn automatic fit stop off (so that you get deterministic results), press opts, turn performance reporting on, press ok, press start. Wait then for few minutes, and discard the first performance number (it has JIT compilation effects). Try again and this time don't discard the number. Try a few times and calculate mean and standard deviation of the fitting time.

Then check out the branch xchart_rebase, rebuild with "ant clean; ant" and do the same thing. It uses my custom version of xchart that has the anti-aliasing turning off feature. Performance should be 1.3% worse. You can replace the xchart .jar with an official release and remove the setAntiAlias lines that result in a failed compilation to see performance is 3.9% worse now.

Note that this is a full application and chart creation is only part of the story. So it could be that XChart is 10x slower than JFreeChart, but since charts are drawn so rarely, it results in only 1.3%-3.9% performance degradation of the overall code.

If you want to see more extreme differences, revert the git change 5e9c41bbc5a667450caef5848f7722173feb59f5 that makes chart drawing occur once per half seconds instead of every iteration. Now XChart is 15% slower if you revert this change and if you enable anti-aliasing.

I will see if I can contribute a benchmark that measures only chart drawing, not anything else.

**Comment by jmtilli** [comment]
I now created chartperf: https://github.com/jmtilli/chartperf

It produces these results:

$ sh make.sh

XChart
15.56user 0.28system 0:09.19elapsed 172%CPU (0avgtext+0avgdata 294640maxresident)k
0inputs+104outputs (0major+72426minor)pagefaults 0swaps

JFreeChart
9.78user 0.25system 0:07.58elapsed 132%CPU (0avgtext+0avgdata 228812maxresident)k
0inputs+144outputs (0major+52658minor)pagefaults 0swaps

XChart anti-aliasing
53.29user 1.24system 0:45.07elapsed 121%CPU (0avgtext+0avgdata 425088maxresident)k
0inputs+104outputs (0major+106037minor)pagefaults 0swaps

This means that XChart creates a lot more garbage when compared with JFreeChart, which is then collected in another thread. Hence performance in single-threaded applications (elapsed) doesn't suffer, but my application is multi-threaded, so we need to look at the "user" time which suffers.

This also illustrates the effects of anti-aliasing. Hence, you should accept my pull request because it improves performance so much.

**Comment by timmolter** [comment]
Good stuff! Thanks. I once tried to optimize speed of XChart by looking for bottlenecks, but I failed to come up with a good way to find the bottlenecks. I tried printing out time differences and a Java code profiler, but with no luck. Do you know of a good way to identify bottlenecks in this case?

**Comment by timmolter** [comment]
Also, since you looked into the JFreeChart code already, do you see anything I should be doing in XChart for better performance?

**Comment by jmtilli** [comment]
I believe the main thing would be to create as little objects as possible. Use primitive type arrays (double[]) internally, not ArrayList of Double objects -- I know I can at least pass double[] to XChart, but looks like it's not using it internally but rather doing Utils.getNumberListFromDoubleArray instead which is a big no-no.

I'm not exactly sure how to find performance bottlenecks in Java code either, but in this case I was lucky to find that CPU% in single-threaded application is over 100%, meaning the only other thread that can be using CPU time is the garbage collector. Overall, it seems like XChart performance in the main thread is very close to JFreeChart performance, but the garbage created is a problem. Mutable objects are better for performance than continuously allocating new immutable objects.

So change that getNumberListFromDoubleArray into cloning of the array (cloning is necessary in case the array changes after being given to XChart)! If the user gives list objects of numbers, convert them to double[] arrays. The same is true for int[] arrays: convert into double[]. Same for float[]. Make all internal interfaces use double[] arrays (with small d, not capital D), in fact! A List object of Number objects means every single data point creates yet another object, creating huge amounts of garbage.

I'm confident the performance can be improved much given the current interfaces, because the garbage created is not built in to the interface of the XChart, rather it is happening internally within XChart. All internal object creations are candidates for removal.

**Comment by timmolter** [comment]
Correct. I'm using internally List<Number>. I'll change it to double[]...

Thank you for you excellent help!

**Comment by jmtilli** [comment]
Great! You have already a new user, as I instrumented that XChart and JFreeChart in my overall application result in 0.06 standard deviations of performance difference, so whatever difference there is, it's not statistically significant anymore. XChart was faster by tiny 0.04%.

**Comment by timmolter** [comment]
Glad to hear it! Thanks again for your help and sharing your benchmark results. I'll work on the legend and the double[] optimization, hopefully soon.
