### ISSUE TITLE
Horizontal-BarChart and Legenda items in row not in column 

### ISSUE THREAD

**Issue by deweweb** [timmolter/XChart#207]
- is it possible to use a horisontal (Y-Axe) Horizontal-BarChart ? (workaround?)
- is it possible to orient items in legenda horisontal not vertical?
Thank you in advance!

**Comment by timmolter** [comment]
> is it possible to use a horisontal (Y-Axe) Horizontal-BarChart ? (workaround?)
Not yet. See: <https://github.com/timmolter/XChart/issues/136>

> is it possible to orient items in legenda horisontal not vertical?
Yes, in the latest snapshot. It will appear in V 3.5.0.

> Thank you in advance!

You're welcome!

**Comment by timmolter** [comment]
Closing due to repeat of: https://github.com/timmolter/XChart/issues/136
