### ISSUE TITLE
Feature request: Series Legend Name

### ISSUE THREAD

**Issue by RNuWM** [timmolter/XChart#218]
Currently, the legend entry string for a series is (logically) the series name. Unless I am missing it, there is no way to independently set the displayed legend entry for each individual series.

The problem is, the series name is "internal" data used in the LinkedHashMap, etc. and all series names must be unique. You cannot have multiple legend entries with the same displayed string. There are also artificial challenges that come up when you internally have multiple data series that appear as a single series to the user (this is my case). 

Adding a series.setLegendName(String) would be a big help. Obviously, it would default to the series name if not set.

Java is not primary language, but I could attempt this if needed.

**Comment by timmolter** [comment]
Sounds good. Should be easy if you want to implement it.

**Comment by RNuWM** [comment]
Will do. I'll implement this next time I'm working on XChart code.

**Comment by RNuWM** [comment]
@timmolter 

Do you have plans of looking into #231? It (I presume) addresses an important deficiency of the library. Simply having two legend entries with the same name is not currently possible.

Alternatively, attached are the very minimal changes I have been using to address #218.

[Series Legend Name.zip](https://github.com/timmolter/XChart/files/1717060/Series.Legend.Name.zip)

![legend with duplicate names](https://user-images.githubusercontent.com/28081765/36108743-66373732-0fd2-11e8-983d-e498fe87f96b.png)

**Comment by timmolter** [comment]
merged.
