### ISSUE TITLE
BubbleChart#addSeries(List...) always interprets x-axis data as dates

### ISSUE THREAD

**Issue by dm3** [timmolter/XChart#225]
Commit https://github.com/timmolter/XChart/commit/a9d81718d22251632d6c25b16b05125cf1febf22 made BubbleChart#addSeries(List...) always interpret x-axis data as dates. It used to work with plain numbers.

This seems like a mistake. How do we get back the previous behaviour?

**Comment by timmolter** [comment]
Fixed. Thanks for pointing that out and my apologies for that! try the latest snapshot build...
