### ISSUE TITLE
Gauge with DialChart

### ISSUE THREAD

**Issue by Tobi2707** [timmolter/XChart#238]
is it possible to create something like a Gauge with DialChart?
I want so show sped values with minimum speed = 0 maximum speed = 300 and the needle should show the average speed.
I can only add series between 0 and 0.99 but i need 0 - 300. Is there a way to get this done?

Thank you :)

**Comment by timmolter** [comment]
You can trying using something like this:

```
chart.getStyler().setAxisTickValues(new double[] { .33, .45, .79});
chart.getStyler().setAxisTickLabels(new String[] { "min", "average", "max"});
```

to translate from 0==>1 to 0==>300.

**Comment by Tobi2707** [comment]
Is it possible to get the source code of your new dial example?
Because I want to create also these "small ticks" and the the color of 0%-20% and 80%-100% areas.

There I find your example really nice
![27112092-45c8795c-50e7-11e7-89a3-e10357d6ab5c](https://user-images.githubusercontent.com/33152599/33822617-7d7efb6a-de58-11e7-9881-75b6f450ff1b.png)

**Comment by timmolter** [comment]
https://github.com/timmolter/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue210.java

**Comment by Tobi2707** [comment]
Ah Thanks for that link, but there I can't find how to add the small "sub-ticks"...

**Comment by timmolter** [comment]
where did you find the above dial chart image? I don't recall ever producing that.

**Comment by Tobi2707** [comment]
found it here:
https://github.com/timmolter/XChart/issues/189

thought it was yours :P

**Comment by timmolter** [comment]
Nope. That was what someone was requesting (feature request). I don't think my dial chart allows for the sub tick marks. Sorry.

**Comment by Tobi2707** [comment]
Ahhh okay sorry, my mistake. But great work your lib. thanks!!

**Comment by hakantkn** [comment]
You can add tick marks with a label of " " to simulate sub tick marks. They will have the same length but with no visible label. See code & screenshot below:
```
    chart.addSeries("Speed", 0.85, "255");
    chart.getStyler().setLegendVisible(false);
    chart.getStyler().setRedFrom(0.7);
    chart.getStyler().setAxisTickValues(new double[] { 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.82, 0.84, 0.86, 0.88, 0.9, 1.0});
    chart.getStyler().setAxisTickLabels(new String[] { "0", "30", "60", "90", "120", "150", "180", "210", "240", " ", " ", " ", " ", "270", "300"});
```
![image](https://user-images.githubusercontent.com/6737748/33830494-75cef30c-de85-11e7-85b8-85ba5c3b5322.png)
