### ISSUE TITLE
Is there a way to show different colors of bars (vertical columns) in a single series in bar chart?

### ISSUE THREAD

**Issue by prakhar230792** [timmolter/XChart#239]
I am trying to show different color across different bars in same series in a BAR chart.
For same series, as of now we have a single color.

A workaround I could think of was to use overlapped bar charts:

Sample Code:

 ```
@Override
  public CategoryChart getChart() {
    // Create Chart
    CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("Score Histogram").xAxisTitle("Mean").yAxisTitle("Count").build();

    // Customize Chart
    chart.getStyler().setLegendPosition(LegendPosition.InsideN);
    chart.getStyler().setLegendLayout(LegendLayout.Horizontal);
    chart.getStyler().setLegendBackgroundColor(Color.WHITE);
    chart.getStyler().setLegendBorderColor(Color.WHITE);
    chart.getStyler().setAvailableSpaceFill(.96);
    chart.getStyler().setOverlapped(true);
    chart.getStyler().setPlotGridVerticalLinesVisible(false);
    chart.addSeries("Person1", new ArrayList<String>(Arrays.asList(new String[]{"Person1", "Person2"})), new ArrayList<Number>(Arrays.asList(new Number[]{90, 0})));
    chart.addSeries("Person 2", new ArrayList<String>(Arrays.asList(new String[]{"Person1", "Person2"})), new ArrayList<Number>(Arrays.asList(new Number[]{0,100})));
    return chart;
}
```

![bar chart with color](https://user-images.githubusercontent.com/10173765/33751335-41a5fd82-dc00-11e7-8839-9d04e08e33e0.PNG)

As can be seen in the code I have made all values 0 except one in every series.

Does anyone see any challenge in this approach.
A major challenge I think could be that for high number of x.y pairs chart generation could be an intensive, time consuming task.
Please share your thoughts.

**Comment by timmolter** [comment]
I think it's a good work around. Eventually I need to allow for setting properties on specific data points though...
