### ISSUE TITLE
Both Y axes of a two Y axis chart are controlled by setYAxisMax and setYAxisMin 

### ISSUE THREAD

**Issue by waltwj** [timmolter/XChart#244]
I have a chart with a y axis on the left and one on the right. The group using the left axis has a min and max value I want to set manually. The group on the right is fine to float normally as the data comes in.
The problem is when I use setYAxisMax and setYAxisMin for the left side, it also limits the scale on the right side. Is there a way to set one side and let the other side float? If not, this would seem like a good feature request.

**Comment by hakantkn** [comment]
Check pull #245

**Comment by timmolter** [comment]
Is this working now with @hakantkn 's PR? I don't have time to test it.

**Comment by hakantkn** [comment]
Yes it solves this problem

**Comment by waltwj** [comment]
I’ve seen no bugs in it.
