### ISSUE TITLE
Pie Charts

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChart#26]

**Comment by eleanora** [comment]
Any updates regarding this feature?

**Comment by timmolter** [comment]
I'm thinking of adding it soon.

**Comment by eleanora** [comment]
Great. I'm counting on it, because I really prefer to use xchart for all my charts rather than use a different library/solution just for the pie charts. Do you think it will be completed within the next 2 weeks or so? :) What is the expected timeline?

**Comment by timmolter** [comment]
Yeah, I think so, but no promises. And it will be pretty basic.

**Comment by timmolter** [comment]
OK, I roughed in the first pie charts in XChart. See `PieChart01` in the source code or the snapshot jars. An official release will come after a while to allow time for a bit of testing. Your feedback would help speed up the process.

**Comment by eleanora** [comment]
Great. Thanks!!! I will try it and let you know if I find any issues.

**Comment by eleanora** [comment]
I tried the new pie chart. For now I found two issues/possible improvements:
(1) For some reason there is padding that I can't get rid of. 
I use the following lines to get rid of the padding, with no success.
chart.getStyleManager().setChartPadding(0);
chart.getStyleManager().setPlotPadding(0);
chart.getStyleManager().setChartTitlePadding(0);
chart.getStyleManager().setLegendPadding(0);

(2) I think it would be very nice if we could use labels next to each pie chart slice instead of the legend (maybe this could be done by adding another type to the legend position that supports adding legend labels next to the appropriate data series, or as alternative set a label for each series). This way the chart would be more concise. The legend takes additional space that might bother some users (like me..) WDYT? Here's an example for what it might look like:

![image](https://cloud.githubusercontent.com/assets/2756945/12220858/ea645374-b78b-11e5-9b06-fb103b99ca3a.png)

**Comment by eleanora** [comment]
(3) Another possible improvement - it would be nice if there was a way to control where the first slice of pie chart starts (say 45 degrees instead of 0 degrees). I noticed that some libraries have this feature.

**Comment by timmolter** [comment]
Thanks for the suggestions. I'll probably work on that within the next month.

What padding do you mean? Between the slices?

**Comment by eleanora** [comment]
OK. Thanks.
The padding around the pie chart.

**Comment by timmolter** [comment]
OK, I see what you mean. I have it hardcoded at 70% of the available size right now. What do you think a good default value would be?

**Comment by eleanora** [comment]
I think the chart should fill all the available size by default (100%). If padding is specified, it should change according to the specified value.

**Comment by eleanora** [comment]
Another important note - some users would probably need to create pie charts of the same size so it's important that labels added next to the pie slices not affect the size of the pie chart itself. It's a problem I encountered in some libraries that I think can and should be avoided.

**Comment by timmolter** [comment]
Yes, definitely.

Also do you think pies should be forced to be circular or be oval to match the shape of the window?

**Comment by eleanora** [comment]
I think they should be circular by default because this is more common, in my opinion.
Maybe a future feature could be to allow the user to change the "oval level"/"oval degree" or just set the chart to oval and then the chart would be created according to the chart width and height.

**Comment by eleanora** [comment]
(4) Another issue I just found - the pie chart implementation assigns colors to the slices automatically which is nice, but if I set colors to each pie chart series (returned by addPieSeries), the colors are assigned to the pie chart slices, but they are not assigned to the corresponding legend label in the legend component.

**Comment by timmolter** [comment]
OK, thanks for letting me know. I'll fix that too.

**Comment by timmolter** [comment]
I did some work on this today. I didn't manage to accomplish everything you wanted, but I did add:

1. ability to set start angle
1. fix legend
1. added styling abilities ("padding", isCircular)

If you want to try it, you'll need to use the new 3.0.0 branch. For the rest of the things you wanted, can you open separate issues, please? Much appreciated!

<img width="800" alt="screen shot 2016-01-11 at 12 28 43 am" src="https://cloud.githubusercontent.com/assets/738972/12224836/4fb160be-b7fa-11e5-85b6-6d519bf8039f.png">


    // Create Chart
    Chart_Pie chart = new ChartBuilderPie().width(800).height(600).title(getClass().getSimpleName()).build();
    chart.addSeries("Gold", 24);
    chart.addSeries("Silver", 21);
    chart.addSeries("Platinum", 39);
    chart.addSeries("Copper", 17);
    chart.addSeries("Zinc", 40);

    Color[] sliceColors = new Color[] { new Color(224, 68, 14), new Color(230, 105, 62), new Color(236, 143, 110), new Color(243, 180, 159), new Color(246, 199, 182) };
    chart.getStyleManager().setSeriesColors(sliceColors);

**Comment by eleanora** [comment]
Thanks. I'll open separate issues for the rest of the things. 
Where can I find the 3.0.0 branch jar in order to try the updated pie chart implementation?

**Comment by timmolter** [comment]
There's no jar yet until I merge the 3.0.0 branch into develop branch. But the source is on github of course.

**Comment by eleanora** [comment]
Makes sense :) Thanks

**Comment by Enigmaticall** [comment]
Can we still enable a legend as opposed to the labels coming off of the pie slices? Can't find how to do that anywhere, thanks for your help!
