### ISSUE TITLE
100 mBTC Bounty - Multiple Y-Axes on one chart

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChart#54]
Like most charting libraries, multiple x-axes per chart should be possible such as shown here: https://bitcoinium.com/ using the Flot Javascript library. Each series should be assignable to an axis. Each axis should be shown on the chart and it should be possible to define whether the axis goes on the left or right side. The data plot should of course scale to the full extend of each axis. 

The original feature request for this can be found here: https://github.com/timmolter/XChart/issues/31

**Comment by shibe2** [comment]
Hi! I'm working on this, and I have a couple of questions.

- What would be the maximum amount of Y axes?
- How multiple axes on the same side of a chart should appear?
- Is compatibility with the existing API required?

**Comment by timmolter** [comment]
Hello!
1. 3 max should be sufficient
1. Similar to what other charting libs do. Simply draw the axes next to each other. Pick the first axes to define the background lines I suppose.
1. No.

**Comment by hakantkn** [comment]
Hi, I want to work on this issue.
