### ISSUE TITLE
ggplot2 style API

### ISSUE THREAD

**Issue by mleoking** [timmolter/XChart#69]
ggplot2 (http://ggplot2.org/) in R implements the graph API described in the book: grammar of graphics. It is then able to make complex plots in 2-3 lines of code. 

![screenshot_1](https://cloud.githubusercontent.com/assets/5763751/2868072/6341257a-d240-11e3-954a-dab3c86408ae.png)

Have look at this video: https://www.youtube.com/watch?v=HeqHMM4ziXA

You will then know why Its API style is now so popular and why people want it API style so much that they translate its API into python: http://blog.yhathq.com/posts/ggplot-for-python.html.

ggplot2 is still using the basic plot functions in R, but just provides a very nice & concise API to describe figures. And it is the API style that makes it so popular.

This makes think, why we do not like Jfreechart. Jfreechart is not bad and its 2d plotting ability is already relatively comprehensive. I now realize the main reason is not really its size (2m is not that big). It is because its complex API. You need to write so many code to plot a simple figure.

That makes think, whether it is possible to write ggplot2 style API in java that unifies Jfreechart (2d) and jzy3d (3d). It may that the API is so nice and concise that people just use the new API instead of using JFreechart, or Jzy3d directly.

I am not sure whether ggplot2 style API is really possible in Java. But I feel, if only aim for simplicity and forget all those rigid rules & styles in Java, a ggplot2 similar API might be possible.

What do you think?

**Comment by timmolter** [comment]
The project: [Joinery](https://github.com/cardillo/joinery) looks like something that could be used as a front end ggplot-like data manager for XChart.

**Comment by lwhite1** [comment]
Joinery looks very nice (hadn't seen it before) but can you get a non GPL license for it?

**Comment by lwhite1** [comment]
FWIW, (shameless plug) you may want to take a look at Tablesaw: github.com/lwhite1/tablesaw. It's not as polished as joinery but has an Apache license and is under very active development.

**Comment by timmolter** [comment]
Tablesaw looks like a clear winner!

**Comment by lwhite1** [comment]
Thanks Tim,

I've added plotting to Tablesaw so you can create plots directly from Tables and Columns without extracting double[] or whatever. Basically, I'm using XChart for the most important chart types (scatter, line, and their derivatives) and filling in around it with other libraries where plots are currently missing: (Bar charts from javafx because they support horizontal bars, histograms from the smile plot library.). I will happily replace those as XChart adds new types, since I can't make the differently libraries look and work similarly enough - plus it's a bunch of work since the APIs are all different :)  

Thanks for all your work with XChart. I really enjoy using it.

**Comment by timmolter** [comment]
Very cool! XChart has histograms. See `BarChart06a`. If that doesn't work for me, let me know why, and I can perhaps change things. Maybe I'll add the horizontal bar charts too.

**Comment by lwhite1** [comment]
Hi Tim, Thanks for the encouragement.

Regarding the histogram, really looking for something with a numeric x axis. I opened a feature request (#157) on that a couple weeks ago. Will definitely look to Xchart first as we add new chart types and upgrade as Xchart enhancements become available.

**Comment by tinylamb** [comment]
if the horizontal bar charts support now?
