### ISSUE TITLE
Day on x scale problem

### ISSUE THREAD

**Issue by tr-rt** [timmolter/XChart#72]
If there are less then 6 days on x scale the scale on the generated graph shows hours instead of days. 

Example code:
http://collabedit.com/xrysj

![graph](https://cloud.githubusercontent.com/assets/7802791/3184640/abc30424-ec87-11e3-8f5c-94e1e99ba27b.PNG)

**Comment by timmolter** [comment]
I did a complete date axis refactor. this should be fixed now in the latest snapshot jar.
