### ISSUE TITLE
Bar chart min and max not working properly

### ISSUE THREAD

**Issue by fac2003** [timmolter/XChart#74]
I am interested in setting the minimum and maximum values on the X and Y axis for my charts.
After I construct a chart, I call
chart.getStyleManager().setXAxisMax( newXmax )

The result is that the axis changes, but the data remain in the same location, not being scaled according to the new axis. This makes the whole plot rather misleading. Here's an example:

Let's start with 
chart.getStyleManager().setXAxisMax( 100 ) (100 happens to be the correct scale for this dataset):

![0-100-scaled](https://cloud.githubusercontent.com/assets/1728407/3738114/3e4dbad4-173d-11e4-8fb2-58a378dab2d2.png)

I now build the same chart, but set XAxisMax to 200:
chart.getStyleManager().setXAxisMax( 200 )

Here's the result. 

![0-200-scaled png](https://cloud.githubusercontent.com/assets/1728407/3738136/6cdd5fda-173d-11e4-82eb-f3dc63ec7b54.png)

You can compare the two plots and see that the data is plotted in exactly the same location, which does not make sense, since it should have been scaled by a factor 2.

**Comment by timmolter** [comment]
Won't fix. Bar chart is for a set number of categories, unlike a line chart. The categories could be Strings or numbers in a non-ascending order, and a min and max doesn't make sense in that context.
