### ISSUE TITLE
100 mBTC Bounty - New Bar Graph Style (Step Chart)

### ISSUE THREAD

**Issue by gavalian** [timmolter/XChart#82]
Hi, I just recently discovered xchart, and I loved it. Has very nice features. and easy to use.
I have seen that this project is being actively maintained, and I thought I would request a feature:
Is it possible to have histograms with outside lines only ? (not filled with color I mean).

I have also saw a request on density plots, that would have been a very nice addition.

**Comment by on247** [comment]
I want to work in this one  ,is it still open?

**Comment by timmolter** [comment]
Yeah, it's all yours if you want.

**Comment by joshafest** [comment]
is it done ? or still open bounty

**Comment by timmolter** [comment]
@joshafest I haven't heard a single peep. @on247 Are you working on this or can @joshafest take a crack at it?

**Comment by joshafest** [comment]
hey man relax....i can help you. In core java. But first i have to go through your xchart.
any way i will try my best , just asked if you are offline.

**Comment by on247** [comment]
I will  be working on it , yeah

**Comment by billyshea** [comment]
Is it okay if I fill this?

I'm working on a solution to this, although drawing the curved line will take a bit longer.

![connectedblocks](https://cloud.githubusercontent.com/assets/17503371/13364510/35d13c24-dc9d-11e5-9da5-7b7be45c6548.png)

**Comment by timmolter** [comment]
The curve isn't necessary. I think @on247 claimed this bounty first, so let's see if he'll give it up for you.

**Comment by billyshea** [comment]
Fair enough.
