### ISSUE TITLE
non closing write operation in XChartPanel - saveJPGWithQuality

### ISSUE THREAD

**Issue by Chiamh** [timmolter/XChart#97]
When saving the Chart within an XChartPanel as JPEG-File the write operation won't close and the file is accessible from outside not until the Java Program with the XChartPanel is ended.

Maybe the FileImageOutputStream within the Method saveJPGWithQuality should be closed manually or maybe a writer.flush() (writer = javax.imageio.ImageWriter) can help.

**Comment by timmolter** [comment]
I just tested this by running `BarChart01` from the `xchart-demo` module and it works fine. I'm on OSX. What OS are you running? Can you please try `BarChart01` or tell me which demo I can run that you've noticed the problem?

**Comment by timmolter** [comment]
@Chiamh I added code to manually close the output stream. I'd appreciate if you could test it. Thanks.

**Comment by Chiamh** [comment]
I found the problem using a `QuickChart` and a normal `Chart` within a small program of mine under **Windows 7 SP1**. With your small update the problem is fixed and it works within my own programs as well as in the `xchart-demo`. Thanks for your quick help!

**Comment by timmolter** [comment]
great! Thanks for reporting the problem!
