### ISSUE TITLE
FileFilters within XChartPanel don't allow switch directories under Win7

### ISSUE THREAD

**Issue by Chiamh** [timmolter/XChart#99]
I like the possibility to save the painted `Chart`s within files. But with the `FileFilter`s not accepting directories, I can only save within the top level directories (Desktop, C:, ..). I you would change the 4 lines within the four `FileFilter` to
```java
if (f.isDirectory()) {
   return true;
}
```
I would be able to save them anywhere.

**Comment by timmolter** [comment]
I wasn't able to reproduce the problem on OSX. I pushed a fix. Would you be so kind to test it and report back?

**Comment by Chiamh** [comment]
Though the change to accept *every* file made it possible for me to change directories under Windows 7 (and therefore solves my original issue), it's now confusing that the filter has no effect any more (besides adding the file extension to the name) and I can see all files with all extensions in the `FileChooser`.
I propose to accept *every folder* (with the code posted in my first comment) but *only the files with the chosen file extension*.

**Comment by timmolter** [comment]
OK, I pushed another update. Thanks!

**Comment by Chiamh** [comment]
Thanks to you - now it work's very well. :thumbsup:
